### ISSUE TITLE
Sections en Sans-Serif

### ISSUE THREAD

**Issue by blegat** [Gp2mv3/Syntheses#127]
Pour les sections, sous-sections, ... j'ai testé de les mettre en sans-serif et ça donne pas mal.
Vous en pensez quoi ? On garde ça ?
Parce que là toutes les synthèses utilise le style vraiment de base de LaTeX on peut un peu penser à les rendre plus jolies :) (juste en changeant `lib.tex` bien sûr).

**Comment by anpar** [comment]
Je suis pour l'idée de rendre les synthèses un peu plus jolies! Mais pour les sections/sous-sections je suis pas fan du sans-serif a priori, je trouve que ça se fond trop dans le contenu. Mais bon c'est sans doute une question d'habitude aussi :)

**Comment by cassiersg** [comment]
Personnellement, je trouve que les classes KOMA-Script (`scrrprt`) sont un peu plus agréables à la lecture (ça correspond plus aux standards de mise en page européens). Ces classes changent la fonte des titres, je pense que c'est du sans-sherif bold par défaut.

Un autre problème de mise en page qu'il y a actuellement, c'est les changements de parties : il faudrait un saut de page à chaque nouvelle partie (et aussi un après la table des matière, à mon avis). Je pense qu'utiliser la classe `report` au lieu de `article` résoudrait le problème, `article` n'est pas conçu pour un texte avec chapitres et parties.

**Comment by Gp2mv3** [comment]
Perso je suis tombé amoureux de l'IEEETran mais bon, on va pas mettre ça comme format sur les synthèses quand même...

**Comment by blegat** [comment]
Selon [ceci](http://tex.stackexchange.com/questions/73141/why-should-i-not-use-the-koma-script-classes),
on dirait que KOMA-Script est mieux à tout point de vue mais que ça change un peu. Peut-être que certaines synthèses écrites avec `article` ou `report` seront difficiles à traduire  ou peut-être que certains seront perturbés par les différences.
Après si c'est des différences plus subtiles dans la customisation de la mise en page, c'est moins grâve.

Maintenant, on pourrait rendre l'utilisation de `lib.tex` plus flexible.
Genre

    \input{../../lib.tex}
    \useclass{article} % ou report ou scrrprt ou IEEETran
    \uselanguage{en} % ou fr
    \usestandardpackages
    \uselistings % ou \useminted
    \usesiunitx % ou \useSIunits
    \hypertitle{... % comme d'habitude mais sans la langue

surtout que là j'ai du faire passer des `\usepackage` dans `\hypertitle` car on donne là langue à ce moment là et du coup c'est un peu naze car dans une synthèse on peut que faire des `\usepackage` avant hypertitle et comme `babel` est importé dans `\hypertitle` c'est parfois problématique.

Ça permettra aussi d'ajouter de la flexibilité. Genre là j'aimerai bien utiliser parfois `minted` ou `siunitx` mais je suis bloqué parce qu'il faut changer toutes les synthèses.

**Comment by blegat** [comment]
Tout bien réfléchi, j'opterais plutôt sur

    \documentclass[SIunits]{summary}
    \hypertitle{...
pour avoir ce qu'il y a actuellement. Et par exemple

    \documentclass[en, minted,scrrprt]{exam}
    \hypertitle{...

pour faire un examen, être en anglais, utiliser `minted` à la place de `listings` et `scrrprt` à la place de `report`.
Faudra juste checker comment faire pour que lorsqu'on compile, il trouve `exam.cls` alors qu'il est pas au bon dossier (il est en `../../../exam.cls` au lieu de `./exam.cls`). Facile à faire avec le Makefile (`ln` juste avant de compiler :P mais faudrait que la compilation marche pour ceux qui utilise un IDE).

**Comment by cassiersg** [comment]
Ça fonctionne pas si on met `\documentclass{../../../exam}` ? Pour les packages en principe ça fonctionne, ça devrait être pareil pour les classes.

**Comment by blegat** [comment]
En effet, ça marche juste comme ça :)

**Comment by blegat** [comment]
Voilà, c'est maintenant beaucoup plus propre :)
J'ai laissé `lib.tex` pour la backward compatibility mais y a plus trop de raison de l'utiliser :)

J'ai aussi changé `lib.mk` que j'ai renommé `root.mk` pour pas qu'il y ait de conflit pour supporter le fait qu'il y a plusieurs types (summary, exercises, exam, interro), ... Il faut aussi mettre à jour `q?.mk` si on faut qu'un cours utiliser `root.mk` du coup tout le quadri a besoin d'être mis à jours ^^ (à par si on mets tous dans le Makefile sans passer par `q?.mk` ).

Dites moi ce que vous en pensez :)

**Comment by blegat** [comment]
Ce qui est un peu chiant c'est un a des warning parce qu'on utilise les packages `../../../eplsummary` qu'on appelle `eplsummary`...
On pourrait résoudre ça en mettant la variable d'environnement à `.:./../..:` et en utilisant `\documentclass{eplsummary}` mais alors ça compilera plus out of the box et je sais pas ce qu'il faut changer sur Windows :P

**Comment by blegat** [comment]
J'ai ajouté dans eplbase l'option `usereportclass` qui permet d'utiliser la classe report au lieu de la classe article :)
La synthèse de `geomat-AUCE1171` par exemple utilise cette option.

Je pense qu'on peut peut aussi ajouter les classes KOMA-script :)
Pour le design des section etc.. on peut faire plusieurs design différent et on peut choisir le design avec une option qu'on donne à eplbase.
Le design est alors implémenté dans eplbase pour chacune des classes (report, article, KOMA-script) ou seulement certaines classes si le design a besoin de truc spécifique de KOMA-script :)

Quelqu'un est chaud pour implémenter un design ? Le plus beau design sera le design par défaut et on peut automatiquement ajouter dans a page de garde l'auteur du design :P

**Comment by fthuin** [comment]
Tu pourrais préciser ton idée ? Tu as un exemple de ce que tu voudrais plus ou moins mettre en place (typiquement un ou plusieurs templates qui te parlent) ? J'ai regardé vite fait komascript pcq je connaissais pas mais il est mis qu'il peut y avoir des problèmes d'incompatibilité avec certains paquets (http://tex.stackexchange.com/questions/73248/what-packages-are-incompatible-with-koma-script). Ca a l'air mineurs comme problèmes mais il faudra faire gaffe quand même.

**Comment by blegat** [comment]
Ça devrait aller pour la compatibilité, au pire on ajoutera des if dans le .cls
Quand quelqu'un fait une synthèse il pourra choisir une classe parmis larticle, report, koma, ... et un style parmis ceux implémentés.
Pour les styles, ça peut être n'importe quoi, on peut faire des thèmes plus chargé et des thèmes moins chargés.

D'ailleurs, on pourrait rajouter le logo EPL et UCL sur la page de garde (note que ça on pourrait le faire pour tous les thèmes).

**Comment by anpar** [comment]
Dans la même idée que tout ce qui existent déjà (eplsummary, etc), on pourrait peut-être créer un template adapté aux formulaires avec (à la place de l'énorme page de garde des synthèses) une entête minimaliste (je pense par exemple au formulaire créé dans #263)

**Comment by blegat** [comment]
Oui, soit ça, soit on laisse une page d'entête qu'on imprime pas comme ça il n'y a même pas de titre dans les pages qu'on imprime -> gain de place :P

**Comment by anpar** [comment]
C'est plus simple en effet :+1:

**Comment by blegat** [comment]
Done in fb25bcfcc5e04605e60aa70fb46fb195e7bbfe52

**Comment by blegat** [comment]
Vous pensez quoi du formatting des questions pour les exams et test (85939ac) ? Je fais pareil pour les corrections d'APE ?

**Comment by anpar** [comment]
Je trouve ça vraiment bien perso!

**Comment by blegat** [comment]
On retirerait pas le retour à la ligne ? Il suffit de changer `[hang]` par `[runing]`. En soit y a quasi jamais de titre et si on veut un retour à la ligne il suffit de faire une ligne blanche

**Comment by anpar** [comment]
Ça fonctionne pas chez moi en changeant ``[hang]`` en ``[running]``, j'ai plein de warning

**Comment by blegat** [comment]
J'ai updaté, je voulais dire `[runin]` :-P
https://fr.sharelatex.com/learn/Sections_and_chapters

**Comment by anpar** [comment]
Ha oui ça marche mieux! Et du coup oui pourquoi pas, c'est vrai que le retour à la ligne ne sert à rien

**Comment by Peiffap** [comment]
Closing this as it seems unlikely to ever be addressed further and is not critical.
