### ISSUE TITLE
Uniformisation des noms

### ISSUE THREAD

**Issue by Nhoutain** [Gp2mv3/Syntheses#157]
Il est peut-être utile d'insérer une nomenclature aux dossiers.

Y'en a certain juste avec des codes (pas lisible à première vue), ou juste avec des noms.

**Comment by blegat** [comment]
Je pensais simplement mettre le nom du cours, on est sûr que c'est unique et non-ambigüe: e.g. SINF1252

**Comment by Nhoutain** [comment]
Pour ma part, je trouve pas ca très parlant et assez lourd qd tu recherche un vieux cour (ou même un cour sans connaître forcément son code..)

Ça ne dérange que moi? :p

Je pensais à "titreTresCourt_code" dans cet ordre la pour faciliter la complétion

**Comment by blegat** [comment]
Ouai c'est vrai, mais il faut savoir que du coup, le pdf s'appellera `Synthèse_q7_titreTresCourt_code.pdf`.
On mettra pas un tiret plutôt alors ? Pour avoir `Synthèse_q7_titreTresCourt-code.pdf`.
Ou alors je change pour avoir `Synthèse-q7-titreTresCourt_code.pdf`.

**Comment by Nhoutain** [comment]
Si en effet. 
Je trouve le première plus esthétique (personnellement)

**Comment by blegat** [comment]
Avec que des underscore ? On peut faire ça. En soit je préfère la deuxième car la séparation entre titreTresCourt et code est pas la même que les autres.

**Comment by Nhoutain** [comment]
Non, je voulais dire la première des proposition pour éviter tout les underscore :
Synthèse_q7_titreTresCourt-code.pdf

**Comment by blegat** [comment]
Ah oui, bah on est d'accord alors :D

**Comment by blegat** [comment]
Dans le code, on met le L ou pas ? LINGI2347 ou INGI2347. En soit il est pas très informatif...

**Comment by Nhoutain** [comment]
En effet

**Comment by blegat** [comment]
L'avantage de juste prendre le code, c'est pour les examens. Si on veut suivre la convention utilisée sur le forum-epl, pour les examens, on doit mettre INGI2347-2015-Janvier.pdf
Du coup, il faudra traduire tous les noms de cours (ici, secu-INGI2347 -> INGI2347).
Regarde la ligne 280 du `README`

**Comment by Nhoutain** [comment]
Le but est d'avoir qqlch de humain friendly si vous voulez avoir des
participations.. et juste le code ça l'est pas...

Note: se baser sur le forum-epl qui est mort, est-ce une bonne idée ? :)

**Comment by blegat** [comment]
Je disais juste pour que tu saches quel était le seul argument contre :) maintenant c'est vrai que les avantages de ton idées sont plus importants que les inconvénients :P

**Comment by Nhoutain** [comment]
D'accord :D

**Comment by Nhoutain** [comment]
#bb6aa8f0db5dc874c9e6ea72f9dcbca97bd47028

**Comment by blegat** [comment]
@Nhoutain Enfin fini les quadri impairs champagnes :D

**Comment by fthuin** [comment]
@blegat en Q7 il reste ELEC2870 :D

**Comment by blegat** [comment]
Done :)

**Comment by Nhoutain** [comment]
Oh yeah, well done @blegat ! Avant le prochain quadri faudrait faire les impaires :D

**Comment by blegat** [comment]
Plus que q4 et q6 :)

**Comment by blegat** [comment]
q6 done :tada:

**Comment by blegat** [comment]
FIXED !!! :) Only remaining one is covered by #319 @Nhoutain
