### ISSUE TITLE
readme ajouter une synthèse 

### ISSUE THREAD

**Issue by fthuin** [Gp2mv3/Syntheses#180]
le README devrait être mis à jour pour reprendre l'utilisation de add.sh de @Nhoutain

**Comment by Nhoutain** [comment]
:+1:

**Comment by blegat** [comment]
@fthuin c'est fait avec ton pdf mtn non ? :)

**Comment by blegat** [comment]
ah non y a encore une section du README qui parle de ça, il faudrait virer

**Comment by fthuin** [comment]
Il faudrait nettoyer le README et ajouter des liens vers le wiki ou vers le PDF (p-ê push le PDF sur le git ?) pcq vu la lisibilité du truc personne doit prendre le temps d'y regarder

**Comment by blegat** [comment]
Le PDF est sur Dropbox, les gens vont chercher les synthèses là non ?

**Comment by fthuin** [comment]
Ah oui c'est vrai, mais moi je vais jamais sur la dropbox donc j'avais oublié son existence... On peut supprimer cette parite du README et fermer cette issue :)

**Comment by blegat** [comment]
Yep, je vais faire ça :)

**Comment by blegat** [comment]
@fthuin : Tu penses quoi de 86935ae ?

**Comment by fthuin** [comment]
C'est nickel comme ça :) (j'ai annoté 2 erreurs dans le commit)

Après les exams j'essaierai de revoir un peu le wiki aussi

**Comment by blegat** [comment]
Oui le wiki est à revoir :P
