### ISSUE TITLE
add.sh ajouter un examen

### ISSUE THREAD

**Issue by fthuin** [Gp2mv3/Syntheses#182]
Le fichier add.sh devrait proposer de créer les examens comme prévus par les autres fichiers, autrement dit

cours-code/exam/année(ex:2014)/month(ex:Juin)/Majeure/ avec les différents .mk dans chaque répertoire et le nom du fichier type cours-code-exam-année-month-majeure.tex

**Comment by blegat** [comment]
Et il faudrait aussi demande s'il faut

* rien mettre: énoncé et solutions
* mettre `SOL=only` dans le Makefile: uniquement solutions (que le pdf avec `-Sol`).
* mettre `SOL=` dans le Makefile: uniquement énoncé.
Ça s'applique pour exam, test, exercises et mcq

**Comment by blegat** [comment]
@fthuin c'est résolu non ?

**Comment by fthuin** [comment]
Oui !
