### ISSUE TITLE
[FSAB1101 - q1/math] Correction dérivée de Taylor

### ISSUE THREAD

**Issue by pgonzalezalv** [Gp2mv3/Syntheses#210]
Bonjour, 

Je remarque qu'il y a une petite erreur dans la somme de la **dérivée du polynôme de Taylor**.
D'après la synthèse, la dérivée du polynôme de Taylor est le polynôme de Taylor d'ordre **n** de la dérivée de la fonction f. Or, en utilisant la définition du polynôme de Taylor, on obtient le polynôme de Taylor d'ordre **n-1** de la dérivée de la fonction f.

**Erreur (lignes 146-147) :**

\[ \left(T_n^{f,a}\right)'(x) =
\sum_{k = 0}^n \frac{f^{(k+1)}(a)(x - a)^{k}}{k!} \]

**Correction proposée :**
\[ \left(T_n^{f,a}\right)'(x) =
\sum_{k = 0}^{n-1} \frac{f^{(k+1)}(a)(x - a)^{k}}{k!} \]

Merci d'avance pour la correction!

**Comment by blegat** [comment]
Bien vu, merci :)
