### ISSUE TITLE
elec-FSAB1201: manque équivalents de Thévenin et Norton, montage transfo - redresseur - filtre et ampli op

### ISSUE THREAD

**Issue by mcouplet** [Gp2mv3/Syntheses#233]
Cette partie a été ajoutée récemment je pense et n'est pas dans le Young.

**Comment by blegat** [comment]
Elle n'était pas enseignée notre année ce qui explique qu'elle manque :-P Il faudrait en effet l'ajouter.

**Comment by blegat** [comment]
@mcouplet Fixed by #234 non ? :)

**Comment by mcouplet** [comment]
Nope, il manque encore le transfo et l'ampli op. Je fais ça dès que possible !
