### ISSUE TITLE
[Compilation] Q7 - INGI2143

### ISSUE THREAD

**Issue by fthuin** [Gp2mv3/Syntheses#235]
Il y a une erreur de compilation pour la synthèse de concurrent systems en Q7 (INGI2143) que je n'arrive pas à comprendre (ça bug sur {Charles Pecheur} dans hypertitle). Il y a moyen de compiler malgré tout mais c'est gênant.

**Comment by blegat** [comment]
C'est parce qu'il utilise `subfig` qui est deprecated et incompatible avec subcaption
