### ISSUE TITLE
elec-FSAB1201-summary : mettre les circuits en CircuiTikZ

### ISSUE THREAD

**Issue by mcouplet** [Gp2mv3/Syntheses#251]
Tous les montages ampli op sont en png, c'est pas très joli, il faut les mettre en `circuitikz`.
Et si quelqu'un a une autre solution pour le graphique associé au bloc alim, ce serait cool !

**Comment by ldevillez** [comment]
J'ai commencé à travailler pour voir si ça rendait bien. Pour le V0 j'ai du mettre une réstance  blanche mais je dois encore la décaller pour que ça soit mieux à moins que quelqu'un ait une autre idée.

![capture d ecran 42](https://cloud.githubusercontent.com/assets/15208526/12080738/ee3152a8-b264-11e5-9f3f-c662f60f81e6.png)

**Comment by anpar** [comment]
http://ftp.math.purdue.edu/mirrors/ctan.org/graphics/pgf/contrib/circuitikz/doc/circuitikzmanual.pdf
En général j'utilise ce qui est expliqué en bas de la page 48 pour dessiner les tensions

**Comment by mcouplet** [comment]
Sinon y a ça qui est très simple !
`(node1) to[open, v^<=$V_0$] (node2)`

**Comment by ldevillez** [comment]
@mcouplet @anpar merci beaucoup j'avais essayé mais j'avais mis un V et non un v donc ça marchait pas ^^. Par contre c'est normal que ma flêche rentre dans le schéma et que je doive légèrement la déplacer ?

**Comment by mcouplet** [comment]
Je vois pas ce que tu veux dire, tu peux mettre un screenshot ?
Et btw, utilise `\begin{circuitikz}[american]`. La plupart des circuits du prof sont dans le style américain et j'ai fait tous les circuits comme ça donc ce serait bien d'uniformiser :wink:

**Comment by mcouplet** [comment]
@blegat Fixed by https://github.com/Gp2mv3/Syntheses/commit/b8ed283d04708a9c91cbecce5b5863bc6467ac93 ?

**Comment by blegat** [comment]
Il me semble que ça fix le soucis oui :) Merci à @ldevillez
