### ISSUE TITLE
Math FSAB 1101

### ISSUE THREAD

**Issue by ldevillez** [Gp2mv3/Syntheses#261]
Alors j'ai remarqué:
- une faute d'orthographe: le case au lieu de le cas (page 15)
- dans le cours actuel la partie matrice et système linéaire vient avant les EV, je sais pas si c'est normal que c'est le contraire dans la synthèse

**Comment by ldevillez** [comment]
je viens de remarqué qu'il est mis (c1 + c2)r1^n + (c2 * r1*delta) * n * r1^n-1 alors que sur les slides de Pereira il est  c1 + c2)r1^n + (c2 * delta) * n * r1^n-1

**Comment by blegat** [comment]
Dans la synthèse, on a laissé le r_1 pour que ce soit égal à l'équation du dessus. Le prof l'a retiré car ça ne fait que changer la constante c_2 donc ça marche toujours.
Il a mis r_1^(n-1) au lieu de r_1^n car comme ça (n * r_1^(n-1)) ça donne la dérivée: (r_1^n)'
Mais c'est vrai que c'est pas clair comme ça, on se demande ce qu'on fait

**Comment by mcouplet** [comment]
Personnellement je trouve ça mieux les EV avant les matrices... Quand je lis la synthèse l'ordre me semble logique, c'est pas choquant. Enfin bon c'est mon avis :-)

**Comment by ldevillez** [comment]
Oki c'est vrai que c'est juste la constante C_2 qui va varier. Mais oui c'est vrai que c'est plus logique :)

**Comment by ldevillez** [comment]
Je suis désolé mais à la fin de la page 17, il est mis:
 L = n - rang f(L)e
mais ça ne serait pas plutôt null L comme ça on aurait Null L + Rang L = dim E ?

**Comment by blegat** [comment]
C'est c'est null, si tu regardes le code j'avais mis `\null` au lieu de `\newnull`, c'est pour ça qu'on le voyait pas :)

**Comment by blegat** [comment]
Mettons les flèches vers la gauche, il me semble que c'est ce que le prof fait :)
