### ISSUE TITLE
elec-FSAB1201-summary : Phaseur

### ISSUE THREAD

**Issue by ldevillez** [Gp2mv3/Syntheses#272]
J'ai commencé le schéma phasoriel
![phaseur](https://cloud.githubusercontent.com/assets/15208526/12197982/51433406-b60c-11e5-8ec3-43c4f8a5b1bd.png)

cependant il est pas génial, quelqu'un a une idée pour l'améliorer ?
Je pensais changer les couleurs et l'aggrandir pour qu'il soit un peu plus visible.

sinon j'ai aussi un problème, l'axe verticale n'est pas en gros alors que je lui ai dis:
```
\draw[thick] (0,-2.5) -- (0,2.5) ;
\draw[thick] (-2.5,0) -- (2.5,0) ;
```

**Comment by blegat** [comment]
Je pense que c'est juste parce que c'est une image vectorielle, si tu zooms ils ont la même épaisseur :)

**Comment by ldevillez** [comment]
fixed by #275
