### ISSUE TITLE
INGI2172 - Database

### ISSUE THREAD

**Issue by fthuin** [Gp2mv3/Syntheses#294]
Le prof a dit que la synthèse était très incomplète (par rapport aux besoins pour l'examen), il faudrait l'améliorer. Il propose de faire des reviews des pull requests, donc s'il y en a il serait bon de lui demander des commentaires.

**Comment by Nhoutain** [comment]
La synthèse reprend les slides (et je ne me rappelle pas avoir vu qql prendre notes à son cours) :p

**Comment by Peiffap** [comment]
The teacher for the class has changed since (2015-2016 was the last year it was taught by Bernard Lambeau, Siegfried Nijssen has taken over since). Closing this issue since the comments in it are probably no longer relevant.
