### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cassiersg** [Gp2mv3/Syntheses#303]
On commence à avoir pas mal de contenu par ici, ce serait bien de pouvoir le rendre facilement accessible.
Ajouter une license permettrait de ne pas avoir de problèmes avec ce qu'on peut ou ne peut pas faire avec les synthèses, notamment si on veut les publier sur un espace plus public que les dropbox EPL (un site web, voire sur wikiversity pour certains cours ?)

Comme licence, je pense que quelque chose comme CC-BY-SA serait intéressant: ça permettrait de s'intégrer avec la plupart du contenu libre disponible (ou alors juste CC-BY ?).

Si on veut faire ça, il faut demander l'autorisation de tous les auteurs des synthèses. Je suppose que ça devrait être possible de contacter presque tout le monde, vu que les premières synthèses datent de 2011.

Qu'en pensez-vous ?

**Comment by blegat** [comment]
J'y ai aussi déjà pensé, il faudrait en effet mettre une licence style Creative Common. Je pense qu'on peut imposer le ShareAlike en plus. @Nhoutain @Gp2mv3 @anpar @fthuin @mcouplet @pverbist95 @ldevillez qu'en pensez-vous ?

**Comment by fthuin** [comment]
Le contenu que je mets ici peut être utilisé, modifié et on peut même retirer mon nom pour moi, donc peu importe, même une WTFPL m'irait :p faites ce qui convient au plus grand nombre :)

**Comment by anpar** [comment]
Bonne idée! Et CC-BY-SA me semble bien :)

**Comment by mcouplet** [comment]
Je m'y connais pas du tout en licenses, j'ai un peu regardé le [CC BY-SA](http://creativecommons.org/licenses/by-sa/4.0/) et je comprends pas trop le 

> for any purpose, even commercially.

Quel serait un exemple d'utilisation commerciale des synthèses ?

**Comment by cassiersg** [comment]
A la très grosse louche, la license CC-BY-SA veut dire qu'on autorise n'importe qui à faire n'importe quoi avec les synthèses, à condition que tout document qui contient du contenu repris des synthèse
+ mentionne ce fait (et cite les auteurs originaux)
+ soit disponible sous la même license (CC-BY-SA).

Donc on n'interdit pas à quelqu'un (prenons l'exemple le plus réaliste: le SICI) de vendre ces synthèses (mais il devra les distribuer sous la CC-BY-SA).
Bref la philosophie est de dire "faites en n'importe quoi, à condition que ...", et on n'interdit pas les utilisations commerciales.

Personellement, je ne trouve pas que ce soit une bonne idée d'interdire les utilisations commerciales parce que
+ "utilisations commerciales" est un truc pas bien défini.
+ ça empêche potentiellement des gens d'accéder/de distribuer le contenu (exemple du SICI...)
+ ça ne nous apporte rien
+ ...

**Comment by ldevillez** [comment]
Hum je pense personnellement que c'est une bonne idée dans le sens qu'on fais ça je vais dire pour aider et que ça permettrait de rendre les synthèses plus accessibles dans le sens que je pense qu'il y a encore pas mal de personne qui ignore la présence de la dropbox.

Et pour reprendre l'exemple du SICI, je pense pas que leur but serait de faire du profit comme ça, si ils les vendent c'est pour éviter les pertes avec l'impression.

**Comment by cassiersg** [comment]
Au niveau "technique", j'ai proposé une implémentation dans #307
J'ai fait une liste de tous les auteurs [dans le wiki](https://github.com/Gp2mv3/Syntheses/wiki/Auteurs-et-license-CC-BY-SA), il y a a 63 à contacter.
Je propose de compléter cette liste et dès que c'est possible, ajouter la license pour chacune des synthèses.

Des commentaires ?

**Comment by cassiersg** [comment]
BOOKMARK: Au passage, j'ai trouvé 4 documents qui utilisent le vieux système `lib.tex`
+ q3/physique/summary
+ q4/chimieorga
+ q4/cindy
+ q4/ELEC1370
A adpater pour pouvoir mettre la license.

**Comment by fthuin** [comment]
Il y a un doublon dans les auteurs entre "Nicolas Kabasele" et "Kabasele Ndonda Gorby Nicolas".

**Comment by blegat** [comment]
@cmomin @Gp2mv3 @Nhoutain @pverbist95 @alokhan @gejacquet @FHachez savez-vous marquer [ici](https://github.com/Gp2mv3/Syntheses/wiki/Auteurs-et-license-CC-BY-SA) votre accord (ou votre désaccord) pour mettre les synthèses à laquelles vous avez contribué sous licence CC-BY-SA ?

**Comment by MartinBraquet** [comment]
Est-ce utile de garder cette issue ouverte?

**Comment by blegat** [comment]
Je pense qu'on peut fermer :)
