### ISSUE TITLE
Organisation du drive (Makefiles)

### ISSUE THREAD

**Issue by bcassiers** [Gp2mv3/Syntheses#310]
Sur le drive, plusieurs dossiers sont créés pour de mêmes cours. Par exemple, dans q2, il y a à la fois "chimie" et "chimie-FSAB1301" et à la fois "elec" et "elec-FSAB1202". Pour Chimie, le summary est séparé de exercises et notes, et pour elec, il y a carrément 2 synthèses différentes. Je ne sais pas si le problème existe dans les autres dossiers.
<img width="762" alt="screen shot 2016-05-18 at 23 39 18" src="https://cloud.githubusercontent.com/assets/7252831/15375833/c2710930-1d51-11e6-9dcf-ec309e823e12.png">

**Comment by ldevillez** [comment]
Hmm ça ne serait pas juste un problème du drive ? Vu que l'on a renommé justement ces dossiers.

**Comment by blegat** [comment]
C'est ma faute, parfois j'oublie de supprimer les dossiers ;)
