### ISSUE TITLE
[Proposition] Table des matières dynamiques

### ISSUE THREAD

**Issue by Feyensv** [Gp2mv3/Syntheses#313]
Le parcours des informations dans les synthèses serait grandement simplifié par l'utilisation par défaut du package hyperref.
Je trouve personnellement très utile, surtout pour de grandes synthèses, de pouvoir accéder directement à une section en cliquant dessus dans la table des matières.

**Comment by anpar** [comment]
Normalement la plupart des synthèses le font déjà, non?

**Comment by Feyensv** [comment]
My bad, il semblerait que l'ouverture directe sur le google drive ne veuille pas permettre cette fonctionnalité au pdf -_-.
Mais en effet, quand je les télécharge, ça marche ^^.
