### ISSUE TITLE
Plus d'options pour le make

### ISSUE THREAD

**Issue by mcouplet** [Gp2mv3/Syntheses#316]
Ce serait bien de pouvoir utiliser d'autres options de `latexmk`, comme le killer feature `-pvc` qui met à jour un `dvi` à chaque fois que le fichier source change :D

**Comment by blegat** [comment]
Je suis d'accord :) Comment tu imagines implémenter ça ?

**Comment by mcouplet** [comment]
une option en plus au make ? je l'aurais bien fait moi-même mais je ne comprends pas tout dans le `root.mk` donc je laisse faire ceux qui l'ont écrit :)

**Comment by blegat** [comment]
Comment veux-tu que l'utilisateur spécifie les options ? On lui demander de modifier des variables dans ` root.mk` ? Ou on fait d'autre build rules genre `make pvc` ?

**Comment by mcouplet** [comment]
Oui faire un build rule c'est ce que je voulais dire :P

**Comment by Jimvy** [comment]
@MartinBraquet @mcouplet peut-on considérer que cette issue est résolue par #537 ?

**Comment by MartinBraquet** [comment]
Bof, je ne suis pas certain que ça fonctionne. Mais je ne vois pas vraiment ce qu'il faut obtenir, et je ne suis pas sûr que cela soit vraiment intéressant honnêtement :smile: .

**Comment by MartinBraquet** [comment]
@mcouplet , tu penses que l'issue peut être fermée ou bien tu as une idée plus précise de l'option à rajouter? :smile:

**Comment by mcouplet** [comment]
On peut fermer :)
