### ISSUE TITLE
eco-FSAB1803: Ajouter 2/3 graphs

### ISSUE THREAD

**Issue by Gp2mv3** [Gp2mv3/Syntheses#36]
Je pense que dans la synthèse d'éco il peut être bon d'ajouter 2/3 graphs dans des annexes ou quoi. Parce que l'analyse de graphs, on en aura d'office à l'examen.

**Comment by MartinBraquet** [comment]
Ceux qui ont lu la synthèse récemment (@Peiffap , @Hyedryn , @Thothore , @GauthierRotsart , @MrGuim ,....) vous pensez qu'il manque encore des graphes?

**Comment by Peiffap** [comment]
La synthèse est vraiment pas hyper complète, ce serait pas mal de contacter la fille qui a upload une nouvelle synthèse sur le Drive (je me souviens plus de son nom) et de mettre la sienne à la place (en plus comme ça elle peut être mise à jour). En plus il me semble qu'elle l'avait faite en LaTeX aussi. Je veux bien regarder à ça quand je rentre de vacances dans 2 semaines 😊.

**Comment by MartinBraquet** [comment]
Celle de 2016 de Eve Leroy?

**Comment by Peiffap** [comment]
C'est celle-là

**Comment by MartinBraquet** [comment]
Oui, elle est 3 fois plus longue, quelqu'un serait motivé de faire un mix des 2, pour ne pas perdre des choses intéressantes de celle qui est actuellement sur github?
Pour les synchros sur le drive, tout est à jour maintenant, et je ferai les synchros régulièrement dès que des .tex sont mis à jour sur github ;) .

**Comment by Peiffap** [comment]
Je veux bien voir si un mix à de l'effet (en espérant pouvoir obtenir le fichier tex de cette synthèse).

**Comment by MartinBraquet** [comment]
OK, je transmettrai le .tex quand je l'aurai. Si quelqu'un d'autre est partant pour relire ta nouvelle synthèse (ou la faire avec toi), qu'il n'hésite pas !

**Comment by blegat** [comment]
Si elles sont dures à fusionner, la plus longue et plus complète peut être mise dans `notes` au lieu de `summary`.
Ou alors on peut faire `summary1` et `summary2` comme pour les formulaires de stat.
Essayer d'avoir une seule synthèse est un bel idéal mais tous le monde a un goût différent et la meilleure synthèse pour quelqu'un n'est pas spécialement la même que la meilleure synthèse pour qqn d'autre donc essayer de converger vers la meilleure synthese pour tout monde est peut être utopique.
Maintenant je n'ai pas lu la synthèse de 2016 donc je ne sais pas si ce que je dis s'applique ici :-P

**Comment by Peiffap** [comment]
L'avis général sur le groupe fb de Bac 2 était que la synthèse courte n'était plus adéquate pour le cours après le changement de profs.

**Comment by MartinBraquet** [comment]
Ok, ça vaut peut-être la peine de la refaire alors, soit en combinant les 2, soit en remplaçant par celle d'Eve (en gardant aussi l'ancien en la renommant avec un old à la fin pour ne pas la perdre, mais on le complierait pas dans ce cas).

**Comment by Peiffap** [comment]
En soi c'est semblable à l'idée du summary1 et summary2. Je pense que c'est le plus simple.

**Comment by blegat** [comment]
On peut peut-être mettre l'actuelle en summary1 alors en mettant une remarque mentionnant ce qu'il manque et ce qui n'est plus à jour

**Comment by MartinBraquet** [comment]
[LFSAB1803 %3A Economie de l'entreprise.zip](https://github.com/Gp2mv3/Syntheses/files/2207221/LFSAB1803.3A.Economie.de.l.entreprise.zip)
Voici la synthèse d'Eve, si on met en summary1 et summary2, je vais adapté mon script qui fait la synchro, car pour le moment, le script ne compile qu'une seule synthèse. :)
