### ISSUE TITLE
Warning "Token not allowed in a PDF string" dans \hypertitle

### ISSUE THREAD

**Issue by Jimvy** [Gp2mv3/Syntheses#372]
> Token not allowed in a PDF string (PDFDocEncoding):(hyperref) removing `\unskip'

Warning de compilation pour de nombreux documents (en tout cas, tous ceux que j'ai testé, info-q1-exam-2011-juin, math-q1-summary, chimie1-exercices et un nouvel examen que je suis en train de rajouter, mais il n'est pas dans meca-q1-notes).
Il est indiqué dans les logs comme ayant lieu au niveau du paramètre "professeurs" dans la commande \hypertitle, ou, si on a spécifié le texte optionnel entre [] de hypertitle, le warning est indiqué comme étant à la ligne contenant le ] fermant.
Ca ne génère pas plus de soucis, tout se passe bien à part cette erreur, mais le simple fait qu'elle existe et qu'elle soit située à des endroits bizarres fait que je m'inquiète légèrement de la stabilité de la commande \hypertitle... ;-)

**Comment by blegat** [comment]
Je pense que c'est dû aux agents dans les noms :-P

**Comment by blegat** [comment]
Je vois pas trop comment éviter le warning :-(
