### ISSUE TITLE
Synthèse LELEC1370 tableau LaTeX

### ISSUE THREAD

**Issue by locolin** [Gp2mv3/Syntheses#385]
J'ai refais le tableau des quadripôles qui avait été fait à la main.

[circuit.txt](https://github.com/Gp2mv3/Syntheses/files/1035687/circuit.txt)
[circuit.pdf](https://github.com/Gp2mv3/Syntheses/files/1035686/circuit.pdf)

**Comment by ldevillez** [comment]
Fixed by #382 i think

**Comment by MartinBraquet** [comment]
@locolin , on peut fermer l'issue?

**Comment by locolin** [comment]
@MartinBraquet oui :) le tableau avait été refait par qqn d'autre avant moi en fait :)
