### ISSUE TITLE
Math 3 examen août 2017 : typo et raisonnement bizarre

### ISSUE THREAD

**Issue by Jimvy** [Gp2mv3/Syntheses#412]
Question 2, point 2, lors de la solution pour Theta, après la séparation des variables, il est indiqué que seul le cas $+k^2$ donne une solution correcte. C'est l'opposé.
Autre soucis, il faudrait que le $\alpha$ passe au dénominateur du premier membre. Ca évite de se trainer une racine par la suite, et c'est la manière générale dont l'équation est résolue dans le cours.
J'ai la flemme de faire un commit juste pour ça ce soir. Si personne ne s'en occupe d'ici demain après-midi je m'en charge.

**Comment by MartinBraquet** [comment]
Pour le k^2, je l'avais déjà fait sur mon fork. :)

**Comment by Jimvy** [comment]
Fixed by #eb6a527e
