### ISSUE TITLE
Contradiction - Examen math 3 août 2015 MB

### ISSUE THREAD

**Issue by jeertmans** [Gp2mv3/Syntheses#417]
Bonjour,

Je pense qu'il y a une contradiction dans la solution de l'examen d'août 2015 de Martin Braquet.

Il est spécifié au débit de l'exercice 1 que le problème doit être résolu en dehors d'un 3/4 de cercle, puis, plus bas, nous émettons l'hypothèse que la solution doit être continue en r = 0. Or, en se référençant à la page 97 du syllabus d'EDP, la condition à appliquer ne serait pas plutôt que la solution doit être finie en r = +/- oo ? Et donc annuler le coefficient devant le r^k et non celui devant le r^(-k).

Merci

[https://uclouvain-my.sharepoint.com/personal/pverbist_oasis_uclouvain_be/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fpverbist%5Foasis%5Fuclouvain%5Fbe%2FDocuments%2FEPL%2DDrive%2FBACHELIER%2FTronc%20commun%2FQ3%2FLFSAB1103%20%2D%20Math%C3%A9matiques%2FExamens%2F2015%5FAo%C3%BBt%2FFSAB1103%2D2015%2DAo%C3%BBt%2DSol%2Epdf&parent=%2Fpersonal%2Fpverbist%5Foasis%5Fuclouvain%5Fbe%2FDocuments%2FEPL%2DDrive%2FBACHELIER%2FTronc%20commun%2FQ3%2FLFSAB1103%20%2D%20Math%C3%A9matiques%2FExamens%2F2015%5FAo%C3%BBt](url)

**Comment by MartinBraquet** [comment]
En fait, je résouds à l'intérieur du cercle, je vais le changer sur le drive. :)

**Comment by MartinBraquet** [comment]
Si il reste néanmoins quelque chose d'érroné dans ma résolution à l'intérieur du cercle, fais en part. =)

**Comment by jeertmans** [comment]
D'accord, merci pour la rapidité !

Oui en fait je trouve ça bizarre car tu dis que la solution R(r) est de la forme C*(r/a)^k + D*(r/a)^(-k), mais la solution fournie par le professeur, et qui est la même dans les autres examens et exercices, est juste C*(r)^k + D*(r)^(-k). Bon au final les deux sont bonnes car il suffit d'adapter les constantes C et D en fonction du cas, mais je ne voyais pas trop l'intérêt ? Est-ce pour avoir une solution finale plus claire au niveau des dimensions (vu que tu auras du r/a donc déjà adimensionnel) ?

**Comment by Jimvy** [comment]
C'était la PR #400 qui n'avait pas été appliquée au Drive. Pour le moment, le OneDrive ne se met pas à jour automatiquement, et il faut remplacer les documents manuellement. Quand j'aurai un peu de temps je regarderai s'il y a moyen de mettre à jour smartcpy pour gérer un dossier OneDrive stocké en ligne.
Pour ton autre question, oui il fait ça pour que la solution trouvée ait des termes adimensionnels dans les parenthèses, de sorte que les constantes à rechercher soient juste dans la dimension de $u$ ; également, ça simplifie souvent l'application des conditions limites, car ça fait un facteur 1.

**Comment by Jimvy** [comment]
Fixed by #35645dfe du coup ?

**Comment by jeertmans** [comment]
D'accord merci :)

**Comment by MartinBraquet** [comment]
@Jimvy , non c'est l'inverse, j'avais mis initiallement "à l'intérieur" et puis j'ai changé il y a qqs mois après ton message me disant que c'était peut être mauvais et qu'il fallait mettre "à l'extérieur" , ce que j'ai fait ds le PR#400. Mais je pense que ma résolution est correcte pour "l'intérieur" et donc que je n'aurais pas du changer (avec la PR#400). :)

**Comment by Jimvy** [comment]
Dans ce cas je n'ai rien pigé à l'affaire alors. Dans la PR 400, le mot "extérieur" est remplacé par "intérieur", et le reste de la résolution considère des conditions pour l'intérieur. A moins que tu parles d'un autre message ? Flemme de farfouiller dans mon historique fb.
Mais bon, le plus important c'est que ce soit corrigé.

**Comment by MartinBraquet** [comment]
Ah oui! Je me suis bien embrouillé, maintenant c'est correct à mon avis.

**Comment by MartinBraquet** [comment]
Fixed  =)

**Comment by MartinBraquet** [comment]
@jeertmans , on peut fermer l'issue?

**Comment by jeertmans** [comment]
@MartinBraquet oui biensûr
