### ISSUE TITLE
Examen chimie(Q3) électrolyse de l'eau 

### ISSUE THREAD

**Issue by jeangillain** [Gp2mv3/Syntheses#421]
Bonjour, je fais mes débuts sur github, je ne sais vraiment pas comment ça marche mais voilà, je pense avoir remarqué une erreur dans l'erreur dans le correctif pour partie de l'électrolyse. 
à l'anode on a bien Ean=1.23+RT/zF*ln([H^+]^4) et cathode E=0+RT/zF*ln([H^+]^4), on a donc E_cell=E_cath-E_an=0-1.23 +RT/zF*ln([H^+]^4/[H^+]^4)=-1.23+0( ça dépend pas de la concentration en H^+ et donc pas du pH. Donc, ainsi pour la question d'après, tu indiques qu'a petit pH la tension à appliquer est plus faible, je pense simplement que la tension ne change pas mais à pH très faible on a beaucoup d'ions, la résistance est alors moins faible et le courant à appliquer est alors moindre. Je pense mais ne suis pas sur. Un tout grand merci

**Comment by jeangillain** [comment]
![capture d ecran 14](https://user-images.githubusercontent.com/35408168/34910051-d5d6631a-f8ad-11e7-87f7-f27740583828.png)

**Comment by MartinBraquet** [comment]
Bienvenue ! 
Une étudiante vient d'épingler ce problème sur le groupe facebook de ce cours, il doit donc s'agir d'une erreur dans le corrctif.
Je te laisse corriger le code source?

**Comment by MartinBraquet** [comment]
@Peiffap , il me semble que tu es en bac 2, serais-tu d'accord de corriger (si il y a bien une erreur) cette question? J'avoue que les réactions redox, ce n'est plus trop dans ma mémoire...

**Comment by Peiffap** [comment]
Je suis bien en bac 2, j'y jetterai un oeil ;)
