### ISSUE TITLE
Liens vers Drive EPL

### ISSUE THREAD

**Issue by Peiffap** [Gp2mv3/Syntheses#424]
Il me semble que les liens dans le README sont encore les anciens liens, avant le passage à Office 365. Il faudrait peut-être les changer, comme l'ancien drive n'est plus mis à jour (je crois).

**Comment by blegat** [comment]
En effet ! Quel est le nouveau lien ?

**Comment by MartinBraquet** [comment]
https://uclouvain-my.sharepoint.com/:f:/g/personal/pverbist_oasis_uclouvain_be/ElZP_ep3eAtMsNkXcBLj0vYB7CZpoJ-UzQu7pzHV6xGMYw :)

**Comment by Peiffap** [comment]
Je pense que tu as oublié quelques autres liens (notamment vers le pdf how-to-contribute) :/
