### ISSUE TITLE
Compilation de fichiers

### ISSUE THREAD

**Issue by Peiffap** [Gp2mv3/Syntheses#426]
Bonjour!

J'avais une petite question quant à l'utilisation de TexMaker pour visualiser les pdfs des synthèses/exams/... Je viens d'installer MacTex et TexMaker sur mon ordi, et j'ai aussi la version desktop de GitHub si ça sert à quelque chose, mais je ne vois pas comment faire pour pouvoir "compiler l'entièreté du projet", ni même comment accéder au repo GitHub dans TexMaker pour interagir avec le code. J'ai regardé les aides how-to-contribute sur le drive, ainsi que l'aide Latex de Benoît, mais celle-ci parle plutôt des commandes Latex. Je me demandais donc comment font les personnes qui mettent le drive à jour pour pouvoir compiler le projet en entier.

Merci d'avance ;)

**Comment by MartinBraquet** [comment]
Il me semble qu'il faut les mettre manuellement sur onedrive, en compilant les fichiers un à un. 
Maintenant que les étudiants ont un peu plus de temps, je serais vraiment intéressé à trouver un moyen pour synchroniser le onedrive avec github. Certains parlaient de smartcp non? Je ne suis pas ultra doué en info mais je veux bien coder ou me renseigner pour le faire. A ce niveau, ça devient vraiment intéressant car beaucoup de fichiers ont été modifiés sur github et ne sont pas encore actualisés sur onedrive. Quelqu'un sait-il exactement comment faire?

**Comment by Peiffap** [comment]
Mais alors comment est-ce que ça se fait que les commandes personnalisées (par exemple, l'environnement de solutions) sont connus? Il semble peu probable que quelqu'un ait manuellement copié et compilé la bonne centaine (au moins!) de fichiers sur ce repo.

**Comment by Jimvy** [comment]
Je ne comprends pas trop ta question. En haut des fichiers, tu as des \usepackage et autres qui réfèrent vers les fichiers situés à la racine du repo, ce qui permet d'utiliser ces environnements personnalisés. Une compilation traditionnelle dans TeXstudio (ou autres, mais perso j'utilise celui-là ;) ) permet d'obtenir le PDF final, qu'il faut encore renommer, et uploader à la main (pour le moment).
Mais oui, pour le moment c'est fait à la main. Avant, c'était synchronisé par Google Drive, et je pense que les fichiers ont juste été copiés lors du passage à OneDrive, et donc qu'ils ne sont plus à jours.
Egalement, la manière "canonique" de compiler les synthèses est via make et les Makefile, sous *nix. Sauf que ça ne marche pas sous Windows (peut-être qu'on peut faire marcher ça via le Bash Ubuntu avec un TeXlive installé, mais je trouve ça assez lourd ^^).
J'ai l'intention de me pencher sur smartcpy (le rendre plus simple ^^) et OneDrive pendant ces vacances.

**Comment by Peiffap** [comment]
Je pense que smartcpy (si je comprends bien ce que ça fait) peut rendre contribuer plus facile, surtout pour les _noobs_ comme moi ;).

Le problème que j'ai, c'est que bien qu'il y ait des usepackage en haut des fichiers, lorsque je lance TexMaker sur mon pc, il ne les connaît pas (eplunits par exemple). Lorsque tu dis "compilation traditionnelle", j'imagine que tu ne copies pas manuellement tous les fichiers qui ont changé à chaque merge dans un énorme projet que tu gardes en local?

Je me rends bien compte que c'est vague et mal posé mais du coup si je savais comment ça fonctionne je n'aurais pas de problème ^^.

**Comment by VanStratum** [comment]
As-tu bien cloné le dépôt github? Les documents emploient des packages personalisés pour mettre les pages d'introduction et autre.

**Comment by Jimvy** [comment]
En effet, smartcpy rendrait tout plus facile. Sur Unix/GNU+Linux/macOS.
En effet, TeXmaker (et TeXstudio aussi) ne proposent pas la complétion automatique pour des packages qui ne sont pas dans le dossier courant, c'est une limitation pour le moment (peut-être qu'il y a moyen d'aider le dev à faire ça).
Généralement, si tu mets à jour un document, tu sais le retrouver par la suite pour l'uploader. Mais c'est vrai que les retards s'accumulent.

**Comment by blegat** [comment]
Pour mettre à jour tous les `pdf`, il suffit de faire `make release` à la racine du repo. [`smartcp`](https://github.com/blegat/smartcp/) va alors essayer toutes les combinaisons d'`arguments` dans `src/config.yml`. Pour les combinaisons qui font un chemin vers un fichier `pdf` existant, ça va le copier dans OneDrive en transformant le nom du pdf comme spécifié dans `config.yml`. Le soucis pour le moment c'est que [`smartcp` ne supporte pas OneDrive](https://github.com/blegat/smartcp/issues/2). C'est aussi [un peu lent de prendre toutes les combinaisions d'`arguments`](https://github.com/blegat/smartcp/issues/3).

L'autre façon que j'utilisait avant OneDrive, c'est de faire `make release` à l'emplacement du document (à côté du `.tex` et du `.pdf`) ce qui synchronise uniquement celui là. C'est plus rapide car ça évite de tout compiler et ça évite de devoir tester toutes les combinaisons d'arguments vu que ça spécifiée les arguments pour arriver à l'endroit d'où on appelle `make release`. Dès qu'on fait un `git pull`, il suffit de regarder ce qui a été modifer et d'aller faire des `make release` aux endroits correspondants. Pour le moment, à cause de https://github.com/blegat/smartcp/issues/2, ça a pris un peu de retard donc il faudrait faire une synchronisation complète une bonne fois pour toute puis la méthode de faire `make release` uniquement que pour ce qui est affiché par `git pull` pourra à nouveau être appliquée.

**Comment by MartinBraquet** [comment]
C'est très lent de faire toutes les combinaisons, pourquoi ne trouve-t-il pas tous les fichiers .tex du repo? Avec la liste des fichiers .tex, il pourrait ensuite les compiler et mettre le pdf au bon endroit? :)

**Comment by blegat** [comment]
Il pourrait aller parcourir tous le dossier et essayer d'extraire les arguments à partir des noms des `pdf`s qu'il trouve mais ce n'est pas vraiment comme ça qu'est conçut `smartcp` :-P

**Comment by jy95** [comment]
@blegat Question performance, ce que j'ai essayé de faire dans mon builder (@MartinBraquet en a fait un fork : https://github.com/MartinBraquet/Syntheses-PDF-Builder/blob/master/master_script.py ), c'est de procéder de la manière suivante : 

1. Création d'un dictionnaire des arguments (fonction `build_dictionary`) (y a sans doute moyen d'automatiser un peu sa création)
2. Trouver tous les tex qui trainent dans le dossier source (fonction `find_latex_files`)
3. En utilisant leur nom, en déduire les propriétés qui s'appliquent (fonction `build_command`) , en préparant la commande de build, tout en signalant ceux ne disposant d'aucun mapping possible (exemple `13.tex`)
4. Création des répertoires non existants (fonction `create_all_directories`) (En procédant ainsi, on évite les problèmes aveugles de création dynamique)
5. Build des fichiers

**Comment by blegat** [comment]
@jy95 Ça m'étonnerait pas que ton script soit plus efficace pour compiler release tout le repo :)

**Comment by Jimvy** [comment]
En tapant `grep -Rin "onedrive" .` je n'en trouve aucune référence. Et malheureusement, il est nécessaire d'utiliser l'API de Microsoft, étant donné qu'on ne peut pas obtenir le dossier OneDrive en local.

**Comment by blegat** [comment]
Une solution pourrait être de faire `make release` dans chaque répertoire trouvé à l'étape 2. par `find_latex_files` lors de l'étape 5. Il suffit de régler https://github.com/blegat/smartcp/issues/2

**Comment by Peiffap** [comment]
Est-ce que le fait que Microsoft est maintenant "propriétaire" de GitHub pourrait aider à la résolution du problème de la mise à jour automatique?

**Comment by blegat** [comment]
Je ne pense pas que ça va aider :)

**Comment by Jimvy** [comment]
A propos : j'ai potentiellement trouvé un moyen de rendre la mise à jour automatique si on est sous Windows 10 (aucune idée si ça peut marcher pour macOS ou GNU+Linux) :
Il est possible de synchroniser en local un dossier partagé si on dispose du client OneDrive officiel : cela passe par l'option "Synchronisation" du site en ligne, qui permet alors d'ouvrir le lien dans OneDrive et donc de télécharger le dossier en local.
A partir de là, si on dispose des droits en écriture (sous W10  Fall Creators Update, avec le client officiel, j'ai pu tester que je les ai mais que les autres n'y ont pas ; je ne sais pas si les droits sont vérifiés par l'application ou par le serveur, donc je ne sais pas si un virus pourrait contaminer le dossier d'un utilisateur en lecture seule - en tout cas, ça peut certainement le faire si on a l'accès en écriture :/ ), il est possible de déplacer des fichiers et des dossiers normaux depuis et vers ce dossier partagé, et donc de faire la synchronisation comme au bon vieux temps.
Il est donc probable qu'on puisse adapter smarcpy et le fichier config.yml pour rendre possible une synchronisation via "make release" etc. J'ai pas trop envie de tout casser donc je n'ai pas encore tenté, mais je creuserai à l'occasion.
Le défaut est évidemment qu'il faut un client OneDrive qui synchronise en local ; sous GNU+Linux, il n'y en a aucun d'officiel, mais peut-être qu'il en existe des alternatifs (https://github.com/skilion/onedrive en est un exemple, mais aucune garantie quant à son fonctionnement). Sous W10, le bash Ubuntu* a aussi la fâcheuse tendance de ne pas synchroniser les timestamps des fichiers avec Windows lui-même, et ce à la fois dans les dossiers "Windows" et les dossiers "WSL".
A suivre pour après la session...
*Je sais que c'est le mal, mais ça marche pas si mal que ça :p

**Comment by Hyedryn** [comment]
Personnellement j'utilise déjà ça pour accéder au drive en lecture seul. 

Le risque est que si une mauvaise manipulation est effectuée sur le pc de l'utilisateur, ça supprime également tout le contenu du drive. 
J'ai déjà une fois à cause d'une fausse manip supprimé quelques (très gros) dossiers de mon drive ucl sur mon pc et ils ont simultanément été supprimé dans le cloud. 
Malheureusement, je n'ai pas eu la possibilité de les restaurer directement depuis le cloud (la corbeille virtuelle était vide ...). Cela veut dire qu'il y a potentiellement un risque de tout perdre. (Après j'ai restauré les dossiers depuis la corbeille de mon pc et j'ai pu les récupérer sans problème, mais un virus ne placera sans doute pas le dossier dans la corbeille :/ ).

Mais sinon globalement le logiciel sous Windows 10 fonctionne super bien et synchronise toujours tout presque instantanément. 

![image](https://user-images.githubusercontent.com/5383293/41170976-10b3ced2-6b4f-11e8-9fd4-c5ac5b402509.png)

**Comment by jy95** [comment]
Le problème que j'identifie dans vos conversation est surtout la synchronisation avec les fichiers. 

Faut bien reconnaître que Micro$oft a bien fait son travail pour rendre l'API très sale à utiliser pour ce cas de figure (pour ceux qui voudraient s'amuser à la lire : [API ](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/driveitem) ).

Le moyen le plus simple serait de disposer d'un système de versionning plus simple, Git par exemple XD
Histoire qu'on dise simplement à l'API wrapper (OneDrive/onedrive-sdk-python)

**Comment by Jimvy** [comment]
Faire un repository de fichiers PDF... Euh, comment dire... Tu oses critiquer l'API de Microsoft de sale ? :p

**Comment by jy95** [comment]
Franchement oui :) Et j'ai pas besoin d'aller chercher bien loin leur aveux de faiblesse : https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs

**Comment by Peiffap** [comment]
@MartinBraquet tu as résolu ce problème?

**Comment by MartinBraquet** [comment]
Oui, je lance le makefile qui 

1. compile tous les fichiers
2. lance un script python qui donne le chemin de dépôt du fichier compilé vers le drive
3. copie le fichier compilé vers mon drive local

Ensuite, je lance un programme (https://github.com/abraunegg/onedrive) pour Linux qui synchronise mon drive local vers onedrive sur le cloud :D

**Comment by Peiffap** [comment]
Excellent, je peux fermer l'issue alors?
