### ISSUE TITLE
Synthèse LELEC1310 

### ISSUE THREAD

**Issue by AurelienBoland** [Gp2mv3/Syntheses#432]
P16 eq33 c'est P=RI^2 et non P=R^2I^2

**Comment by blegat** [comment]
cc @anpar @cassiersg

**Comment by cassiersg** [comment]
à priori ça semble logique... @AurelienBoland tu peux ouvrir une pull request ?

**Comment by AurelienBoland** [comment]
J'ai jamais trop utilisé github ça te dérange si je te laisse le faire ?
