### ISSUE TITLE
interro mars 2017 elec1370

### ISSUE THREAD

**Issue by GauthierRotsart** [Gp2mv3/Syntheses#434]
Bonjour, je suis nouveau sur Github et je ne comprends pas très bien comment modifier un document. En effet, il me semble que dans le document "Interro 2017 Elec 1370", la source de tension est "branchée à l'envers". De plus, quelques fautes d'orthographe seraient à corriger. Comment peut-on changer cela?:)
Gauthier

**Comment by blegat** [comment]
Bonjour,
@fthuin a fait une explication [ici](https://drive.google.com/file/d/0B1axlYz3_XXKRzdGVWdGdUZ6UGs/view). Dis-nous si ça aide :)

**Comment by ldevillez** [comment]
La source est dans le "bon" sens sur git mais pas sur le sharepoint j'ai l'impression. Est ce que tu aurais l'énoncé de la question ? :)

**Comment by GauthierRotsart** [comment]
![capture2](https://user-images.githubusercontent.com/36813088/36970548-463f1826-2069-11e8-8b0e-251aa99b226e.PNG)
Merci, oui ca m'aide!:)
Je ne sais pas si la photo va s'afficher, mais apparemment, ce serait l'enoncé de l'interro de l'année passée :)

**Comment by GauthierRotsart** [comment]
Du coup, la manière dont la source de tension est mise sur le document du drive est inversée et donc, tous les calculs ne correspondent pas du tout au circuit :)

**Comment by MartinBraquet** [comment]
Je l'ai mis à jour sur le drive.
C'est normal vu que la synchro github-drive ne se fait plus depuis 1 an maintenant...

**Comment by MartinBraquet** [comment]
@GauthierRotsart , on peut fermer l'issue?

**Comment by GauthierRotsart** [comment]
oui ;)

**Comment by MartinBraquet** [comment]
Parfait, je crois que tu sais le faire en cliquant sur un bouton en haut de la page =)
