### ISSUE TITLE
q6/mcp/summary-2017 ne compile pas

### ISSUE THREAD

**Issue by Jimvy** [Gp2mv3/Syntheses#443]
De manière assez logique, le fait que le fichier se trouve dans un sous-répertoire fait que le chemin "../../../eplsummary" n'est pas correct. Et le changer pour "../../../../eplsummary" ne corrige pas le problème, car LaTeX n'est alors pas capable de trouver le fichier "../../../eplbase"... vu qu'il ne suit pas la logique d'un chemin relatif.

**Comment by MartinBraquet** [comment]
Moi je garderais uniquement la plus à jour, au pire on peut mettre l'ancienne dans ce sous-dossier (donc elle ne se compilera pas) et on met la nouvelle dans le dossier principal pour qu'elle compile.

**Comment by Jimvy** [comment]
Ca peut se faire comme ça en effet. Mais bon, l'idéal serait de rendre LaTeX un peu plus intelligent (ou un peu moins stupide :p )

**Comment by MartinBraquet** [comment]
De toute façon, il n'y a pas de makefile dedans et , donc c'est impossible de le compiler comme les autres automatiquement avec Make. Du coup, on peut mettre le nom classique pour la nouvelle et on ajoute `-old`pour l'ancienne en les laissant toutes les deux dans le même dossier pour qu'elles compilent toutes les deux (en sachant que seule la nouvelle sera uploadée sur le drive).
