### ISSUE TITLE
Faute de français dans la synthèse d'autolin

### ISSUE THREAD

**Issue by Jimvy** [Gp2mv3/Syntheses#445]
Section 4, "Root Locus", "On appelle 'Root Locus' la location des racines du polynôme caractéristique". En français ça s'appelle la position, ou à la limite la localisation si c'était une synthèse de géographie ;)

**Comment by Jimvy** [comment]
Dans la même veine, "Figure 5 - Zônes...". C'est bô.

**Comment by blegat** [comment]
Merci :)
