### ISSUE TITLE
[Feature request] Suggestions d'informations complémentaires dans hypertitle

### ISSUE THREAD

**Issue by Jimvy** [Gp2mv3/Syntheses#449]
Depuis pas mal de temps je me dis qu'il serait bien pratique d'ajouter quelques features dans les titres des synthèses, comme :
- Indiquer l'ID du commit lors de la compilation du document. En effet, la date n'est pas une indication suffisante de la version du code source utilisée pour le compiler, ça donne surtout une idée. Le problème est de plus en plus criant depuis que le OneDrive n'est plus mis à jour automatiquement (même si, j'ai trouvé qu'on pouvait récupérer les documents en local, donc il y a peut-être moyen de réparer smartcp ou autres). Je vois deux manières de faire ça :
  - lors de la compilation, on exécute une commande git pour savoir quelle est la bonne version. C'est certainement faisable si on utilise `make`, un peu moins si on utilise directement la compilation des logiciels "classiques" (il faudrait que LaTeX puisse lancer une commande, ce qui semble très limité). Il faudrait aussi voir ce qu'il se passe quand on télécharge sans utiliser git.
  - à chaque `git commit`, le Makefile est mis à jour pour inclure l'identifiant du commit. De manière assez évidente, ça implique qu'on puisse récupérer l'ID d'un commit avant que celui-ci n'existe, ou qu'on fasse deux commits différents (un pour les sources, un pour le Makefile). Peut-être effectuer cette opération lors du merge de la PR ?
- indiquer si l'examen est un examen de majeure ou de mineure. Après, au vu de la réforme du bac, ce ne sera peut-être plus nécessaire...

Voilà, quelques suggestions qui circulent dans ma tête.

**Comment by Jimvy** [comment]
Dans ma tête, le commit sur lequel on compile (le dernier commit à avoir touché aux sources pourrait également être fait, en chipotant un peu avec les commandes git). Mon idée c'est que lorsque quelqu'un compile le PDF, on récupère l'ID du commit, comme ça s'il recompile le PDF deux jours plus tard, on verra que rien n'a en théorie changé, seule la date. Et on peut imaginer que ce soient des ID de commits de PR également, pas nécessairement des commits déjà mergés. Juste une manière d'avoir une référence vers la "version" du code.
Pour ce qui est d'en faire un hyperlien : j'y avais pas pensé, mais ça risque de faire quelques dégâts si quelqu'un compile alors que le commit n'a pas encore été mergé. Il faudrait voir si Github est assez intelligent pour aller trouver des ID des commits dans les autres repos s'il n'est pas dans le repo principal. Ceci dit, au pire c'est un "deal with it" de parfois avoir un commit qui n'existe pas.
En sachant que le but c'est que les documents restent compilables sous Windows (dans une certaine limite) : personnellement j'utilise généralement la fonction de compilation de TeXstudio et n'utilise make que pour produire les versions à mettre sur OneDrive. Ca fait beaucoup de contraintes malheureusement...

**Comment by ldevillez** [comment]
On pourrait rajouter un fichier dans le repo qui ferait la correspodance entre synthèse et numéro de commit:
- Quand on compile une synthèse on va chercher le numéro de commit 

Et puis trouver un moyen d'avoir les numéros de commit à jour avec un git hook ou bien une commande dans le makefile. Après il faudrait se renseigner sur la réalisation.

**Comment by VanStratum** [comment]
> Pour ce qui est d'en faire un hyperlien : j'y avais pas pensé, mais ça
> risque de faire quelques dégâts si quelqu'un compile alors que le
> commit n'a pas encore été mergé.

Si le lien pointe vers
https://github.com/Gp2mv3/Syntheses/commit/<id_commit> , github sera
capable d’aller chercher dans les forks du dépôt. Par contre il ne dit
pas explicitement que le commit ne se trouve pas sur le dépôt d’origine.

**Comment by MartinBraquet** [comment]
Quel est l'intérêt d'avoir le dernier commit?
S'il n'y a pas de PDF pour le doc qu'on veut compiler, on est obligé de compiler.
Et s'il y a un PDF, on utilise en ligne de commande `latexmk`(une des commande dans root.mk`qui va mettre à jour le pdf uniquement si le .tex a changé.

**Comment by Jimvy** [comment]
L'intérêt est que la date seule ne suffit pas à déterminer la version d'un document : des dates différentes ne signifient pas que le contenu est différent, et des dates identiques ne signifient pas qu'ils sont semblables.
Je rappelle qu'il y a parfois d'autres documents qui circulent dans les groupes, sur les forums etc... qui ne proviennent pas forcément du Drive officiel... Surtout que les gens vont être perturbés par la présence de deux Drive au contenu très similaire mais pas forcément à jour.

**Comment by MartinBraquet** [comment]
> L'intérêt est que la date seule ne suffit pas à déterminer la version d'un document : des dates différentes ne signifient pas que le contenu est différent, et des dates identiques ne signifient pas qu'ils sont semblables.
C'est réglé avec les makefiles ça, je ne comprends pas ce qui pose soucis...

> Je rappelle qu'il y a parfois d'autres documents qui circulent dans les groupes, sur les forums etc... qui ne proviennent pas forcément du Drive officiel...
Je ne comprends pas ce que tu veux dire.

> Surtout que les gens vont être perturbés par la présence de deux Drive au contenu très similaire mais pas forcément à jour.
Si tu parles du Drive de @pverbist95 , il sera supprimé avant la rentrée normalement.

**Comment by Jimvy** [comment]
Je comprends bien que tu ne comprends pas...
Le problème que j'ai avec le système actuel, c'est que si je compile une synthèse le 2 mars, que je la distribue à d'autres personnes, puis que le 15 mars je recompile la même synthèse, la met dans le Drive, puis que le 9 septembre quelqu'un télécharge les sources et recompile la même synthèse qui n'a pas été changé, on se retrouve avec 3 fichiers "synthèses" différents, et les gens vont avoir du mal à faire la différence.
Certes, avec un Drive centralisé, le problème ne se pose quasi pas, car il n'y a qu'une seule version à chaque moment. Mais inévitablement la non-centralisation va arriver avec des gens qui compilent chez eux, ou qui font des backups et qui redistribuent des fichiers qui ne sont plus à jour, et qui ont peut-être été recompilés entre-temps.
Dans la même idée, si une synthèse est mise à jour deux fois dans la même journée, ben on va avoir deux dates identiques mais au contenu probablement différent ; et en période d'examen (moment où ça a plus de chances de se produire), les étudiants ne vont probablement pas aller checker si ils ont la bonne version tous les jours.
Chez nous, le Drive est synchronisé en local. Chez les autres, ce n'est pas forcément le cas, et les téléchargements risquent de générer une foultitude de fichiers "différents" alors qu'ils sont les même.
Après, mettre l'ID du commit est probablement trop technique (et il faudrait le faire marcher sur Windows aussi, ou au moins avoir un substitut correct).

**Comment by MartinBraquet** [comment]
Oui je vois, je ne me posais pas la question puisque je me disais qu'il n'y aurait que moi qui ferait la synchro sur le Drive, vu que je suis un des seuls à parvenir à le faire avec les makefiles et un programme de synchro onedrive/repo local sous Linux. Si je le fais chaque semaine, vu l'état peu entretenu de ce repo pendant l'année (max 3 PR par semaine), je me disais qu'il n'y aurait pas de soucis.
Pour le drive "non-centralisé", je pense que les étudiants savent bien que la version à jour est celle sur onedrive, donc ils auront d'office un version out-of-date si ils chipotent sur Facebook.
Donc si on veut juste savoir quelle est la version, on peut déjà checker sur onedrive (l'officiel) si le PDF que l'étudiant regarde possède la même date de compilation que sur onedrive, puisque je ne mettrai sur le drive que les nouveaux PDF's, donc avec le fichier .tex modifié récemment. 
Pour un étudiant, ça revient à autant de "manipulations" à faire plutôt que de devoir aller sur github vérifier l'ID du dernier commit... Je ne crois pas que cette ID parle à beaucoup de gens, en dehors de ceux en info, il n'y a quasi personne, donc ils ne pourront rien vérifier avec ça.
Qu'en penses-tu?

**Comment by Jimvy** [comment]
J'ai réussi sous Windows à _risquer_ d'avoir les 16GB ; j'ai vite annulé le téléchargement, faudrait que je le fasse un jour.
Mais dans ce cas, tu fais comment pour mettre à jour le OneDrive ?
(Normalement j'ai aussi envoyé un commentaire différent par mail, on verra s'il arrive aujourd'hui.)

**Comment by MartinBraquet** [comment]
Oui, ton mail est arrivé 4' après ton commentaire.
Je synchronise sous mon boot Linux avec ce repo github: https://github.com/abraunegg/onedrive.
Il est bien actif et progresse de jour en jour mais en tout cas, je n'ai aucun soucis avec. Il enregistre ce que j'ai modifié sur mon Drive local, du coup il ne met qu'une poignée de minutes pour uploader les modifs locales sur le net. Sous Windows, il faudrait un programme similaire mais ça doit être plus compliqué vu que Linux est mieux branché "ligne de commande".

Pour le serveur qui build tout automatiquement, pourquoi pas, je peux aussi tout compiler chaque semaine/mois, au lieu de compiler uniquement ceux qui ont changé, mais c'est plus long...

**Comment by Peiffap** [comment]
En ce qui concerne les dates/ids de commit: pourquoi ne pas pas une première ligne avec l'id du dernier commit changeant ce fichier et une deuxième avec la date de ce commit comme proposé plus haut? Comme ça les info's ont leur séquence aléatoire et les autres ont une date plus lisible.

**Comment by MartinBraquet** [comment]
Si on veut l'ID du dernier commit, on ne peut pas le mettre manuellement dans le .tex quand on modifie le document, il faudrait donc un document extérieur qui associe à chaque .tex un ID et une date.
C'est possible selon mes recherches. On peut faire `git log -n 1 --pretty=format:%H -- circ-ELEC1530-summary.tex` pour avoir le dernier commit de cette synthèse. 
Et pour la date:
```
echo "$(git log -n 1 --pretty=format:"%ai" -- circ-ELEC1530-summary.tex)" | sed -r 's/([0-9]+)-([0-9]+)-([0-9]+) ([0-9]+):([0-9]+):([0-9]+) ([^ ]+)/\3\/\2\/\1\ (\4\h\5\) /'
```
qui fournit `19/11/2015 (22h37)`.

Je peux exécuter ces 2 commandes dans le makefile `root.mk`en plus de la compilation et ça me semble bon.

**Comment by Jimvy** [comment]
Un document extérieur, ou simplement une sorte de "define" passé à latexmk lors de la compilation, et dont on testerait l'existence avant d'inclure impunément.

**Comment by MartinBraquet** [comment]
Oui, c'est mieux que le doc externe, je suis en train de modifier ça, je le pusherai sur #513 . 
On passe juste l'ID et la date dans la commande make.

**Comment by MartinBraquet** [comment]
Oui, c'est mieux que le doc externe, je suis en train de modifier ça, je le pusherai sur #513 . 
On passe juste l'ID et la date dans la commande make.

**Comment by MartinBraquet** [comment]
Oui, c'est mieux que le doc externe, je suis en train de modifier ça, je le pusherai sur #513 . 
On passe juste l'ID et la date dans la commande make.
Voilà ce que ça donne, c'est bien ça non? :)
![image](https://user-images.githubusercontent.com/25173236/42816249-85d32a98-89ca-11e8-9601-36bac793c774.png)

**Comment by Jimvy** [comment]
Comme indiqué dans la PR, il me semble que cela satisfait aux conditions. :D 
Après, il faudrait voir dans quelle mesure ça fonctionne sous d'autres OS/setup ; les contributeurs n'ont pas forcément de jouer du terminal sous GNU+Linux
