### ISSUE TITLE
Exos INMA1702

### ISSUE THREAD

**Issue by Peiffap** [Gp2mv3/Syntheses#457]
Les corrigés des exos d'opti sont pour l'instant dans un reportage séparé de celui-ci (Il y a encore 2 autres cours qui sont dans le même cas je crois). Il me semble qu'il serait judicieux de les rajouter sur ce repo-ci afin de garder tout en un seul et même endroit non?

**Comment by blegat** [comment]
Pour opti, ça a un statut particulier parce que c'est les exercices et solutions officielles, c'est pourquoi c'est dans un repo du groupe [UCL-INMA](https://github.com/UCL-INMA/LINMA1702-exercices)

**Comment by Peiffap** [comment]
Et du coup c'est encore entretenu ce repo? Il me semble que plus rien n'y a été commit depuis quelques années.
