### ISSUE TITLE
Gros accident d'historique

### ISSUE THREAD

**Issue by Jimvy** [Gp2mv3/Syntheses#460]
Les commits 0fa1773fbcbc181cfb0edf03578f88604b8c624e et 3fd8dca8e9f8c140447656d26550f36a639d8e5c ont provoqué un joli bazar dans l'historique des fichiers : tous les fichiers des dossiers q1 à q8 ont été renommés temporairement avec le "src/" qui a disparu, ce qui fait que dans les logs, tous les fichiers apparaissent comme ayant été pour la dernière fois modifiés par Hyedryn.
C'est particulièrement agaçant lorsqu'on tape une commande telle que "git log --stat" pour par exemple voir ce qui a été modifié (heureusement, git n'a l'air de montrer le bazar que depuis le dossier racine ou le dossier src). Pour la petite histoire, "git show --stat" de ce commit affiche pas moins de 2240 lignes ^^
Juste pour signaler ce petit soucis d'historique.

**Comment by blegat** [comment]
J'ai fait un rebase pour supprimer les commits, ça devrait avoir résolule soucis. Dis moi si ce n'est pas le cas :)

**Comment by blegat** [comment]
Si vous aviez fait un pull récemment, ça risque d'un peu tout casser chez vous
Pour vous en sortir, faites
/!\ ça supprime les commits de `master` qui ne sont pas sur origin/master
```
$ git fetch origin master
$ git checkout master
$ git reset --hard origin/master
```

**Comment by Jimvy** [comment]
Wow, c'est remonté assez loin ^^ il y avait juste les commits à partir de "Merge pull request #452 from Hyedryn/master" non compris qui étaient downstream des deux commits qui ont un peu mis les choses sales.

**Comment by blegat** [comment]
Oui j'ai juste demandé à `git rebase` de dropper ces deux commit mais il a détecté des mauvais merge qu'il a voulu éditer aussi

**Comment by Jimvy** [comment]
C'est un comportement bien étrange ça.

**Comment by Jimvy** [comment]
Je me faisais la réflexion suivante :
Actuellement, il y a à peu près une demi-douzaine de personnes qui doivent avoir mis à jour leur repo, en local au moins, avec la version rebase de master : Hyedryn, Peiffap, jdewasseige, Thothore, blegat et moi-même. Il y en a peut-être plus qui ne sont simplement pas actifs ces derniers temps, mais probablement pas plus qu'un facteur 2.
Il y a par contre bien plus de personnes chez qui le repo local et/ou le repo online est à une version de master qui se trouve après le premier commit 9022bb, quelque part sur la partie réécrite de l'historique. A vue de nez (via l'onglet Network), j'en compte près d'une dizaine : jy95, VanStratum, bnothomb, destmaxi, rlepretre, AurelienBoland, Maxmawt, GauthierRotsart, et c'est sans compter les gens qui ont peut-être cloné en local sans cloné sur Github. Et pas mal de commits sont basé sur ces branches (j'en ai 8 personnellement ^^)
Après moult commandes (`git cherry-pick`, `git merge --no-commit --no-ff` et `git commit --author="Benoît Legat <benoit.legat@gmail.com>" --date="..."` sont mes amis), je suis arrivé chez moi à virer les deux commits incriminés, ainsi que le merge entre les deux, et à garder l'historique plus ou moins clean (il y a juste 8 commits qui disparaissent, depuis le 2 juin). C'est la branche https://github.com/Jimvy/Syntheses/tree/master-clean. J'ai également encore gardé l'ancien master (en attendant la fin du blocus, autant éviter les rebase).
Dès lors, ne serait-il pas mieux d'utiliser une solution un peu moins impopulaire et se contenter de 8 commits de différence, tant qu'on est encore dans l'ambiance, plutôt qu'une solution avec une centaine de commits de différence qui va surprendre bien du monde dans quelques semaines ?
(Je suis prêt à aider les pour ce qui est des commandes à taper, je finis par en avoir l'habitude. Et c'est un peu de ma faute que la situation est ce qu'elle est.)
(Par contre, ce serait bien qu'on demande l'avis des gens avant de faire une opération potentiellement destructive.)

**Comment by Peiffap** [comment]
En soi je pense que pour la très grande majorité des gens qui ne sont pas à jour avec ce repo-ci pour l'instant n'ont pas beaucoup de changements par rapport à celui-ci. Il serait relativement facile pour eux de delete puis reclone le repo, éventuellement en sauvegardant dans un (ou des) fichier(s) différent(s) les documents dans lesquels ils ont apportés des changements, si il y en a. C'est ce que j'ai fait en barbare qui ne comprend rien à git et ça m'a pris quelques minutes, grand max. Après c'est clairement pas la plus élégante des solutions...

**Comment by blegat** [comment]
@Jimvy merci ! J'ai pushé ta branche :)
