### ISSUE TITLE
[ECGE1315] - Duplica de synthèse

### ISSUE THREAD

**Issue by MrGuim** [Gp2mv3/Syntheses#466]
Hello,

J'ai fait une synthèse pour le cours de Stratégie d'entreprise ECGE1315. D'une part parce que la structure de la synthèse déjà présente ne me convenait pas du tout (Je trouve qu'il y a un manque de cohérence) et que le cours a beaucoup évolué. Néanmoins, je ne sais pas comment poster ma synthèse. Quelle est la meilleure solution pour que les deux synthèses puissent coexister ? Si il y a en pas faut-il vraiment supprimer la synthèse de l'autre étudiant ?

Gui

**Comment by fthuin** [comment]
@MrGuim Si ta synthèse est plus à jour et (aussi|plus) complète que celle publiée ici (par moi), remplace celle qui existe. Pour la clarté du repo, il vaut mieux privilégier les nouveaux contenus à partir du moment où ils sont au moins aussi qualitatif/quantitatif.

**Comment by MrGuim** [comment]
@fthuin Sûr ? Parce que je ne veux pas que ton travail soit laissé de côté. De plus, il y a des points que je ne reprends pas comme, par exemple, une partie avec la définition de plusieurs concepts dans une même section. Ma synthèse comporte également moins de schémas (e.g. l'horloge de Bowman) qui peuvent parfois facilité la compréhension de certains points de théorie. Les points de vue que nous avons pris sont tous deux différents quant à la conception même de la synthèse.

**Comment by MrGuim** [comment]
Je le note en commentaire ?

**Comment by VanStratum** [comment]
Plutôt comme un petit note dans le début du document je dirais, du style
\section*{Note}
    lorem ipsum dolor...

**Comment by MrGuim** [comment]
Done.
