### ISSUE TITLE
Pas de numéro dans les titres

### ISSUE THREAD

**Issue by MartinBraquet** [Gp2mv3/Syntheses#468]
Je suis sur KILE et il ne m'affiche pas les numéros des sections et sous-sections dans le pdf quand je suis sur ce fork. Quelqu'un sait pourquoi? Ce serait un package qui pose problème avec ma version?
![screenshot from 2018-06-11 21-51-45](https://user-images.githubusercontent.com/25173236/41253833-d9cd32c6-6dc1-11e8-9e0c-d112667c451f.png)

**Comment by Jimvy** [comment]
Tu as su trouvé une solution ou le problème est toujours présent ?
Selon moi, ça a peu de chance d'être dû à Kile. Regarde si tu as le même soucis dans un autre lecteur PDF, et regarde, en compilant à la main (via make ou via latexmk suivi de toutes ses options) s'il se plaint de l'absence d'un package.
C'est quel fichier ?

**Comment by MartinBraquet** [comment]
J'ai ce problème depuis toujours sur Linux, alors que ça fonctionne sur TexMaker sous Windows.
J'ai tapé 
 `pdflatex mft-MECA1321-exam-2017-Juin-Maj.tex`
mais ça ne va pas non plus, j'ai l'impression que c'est dû aux packages dans ce fork vu que ça fonctionne si je fais un document classique.

**Comment by blegat** [comment]
Le warning n'est pas important, c'est juste que le nom du package ne correspond pas au chemin. Pour que ça corresponde il faudrait faire un lien symbolique dans le dossier de chaque synthèses/exam/... pour chaque package utilisé...

**Comment by MartinBraquet** [comment]
Pourquoi ça ne correspond pas alors qu'on met des ../ ? =)
Et il n'y a pas moyen de les mettre ces liens symboliques (je préfèrerais n'avoir que des avertissements dûs à ce que j'ai écrit dans mon document) ?

**Comment by fthuin** [comment]
Quelle version de texlive tu utilises? Par défaut sous Ubuntu il me semble que c'est 2015. Je me rappelle avoir eu cette erreur à un moment à cause d'un package trop vieux, tu pourrais essayer la [version 2016](http://tipsonubuntu.com/2016/09/16/install-tex-live-2016-ubuntu-16-04-14-04/)

**Comment by Jimvy** [comment]
Pour le warning des chemins, c'est parce que LaTeX reste LaTeX : un logiciel conçu dans les années 80 basé sur un autre logiciel conçu dans les années 70, et qui n'avait pas la prétention de gérer les différents cas d'utilisation modernes du système.
Pour les liens symboliques : ça ne marcherait pas sous Windows. Du coup, avoir quelques warnings qui sont de toutes façons toujours les mêmes ne pose pas trop de problème lorsqu'on cherche les autres warnings pouvant avoir lieu.

**Comment by Hyedryn** [comment]
J'ai eu le même problème avec Textlive 2015 sous ubuntu.
Ceci [https://tex.stackexchange.com/questions/299969/titlesec-loss-of-section-numbering-with-the-new-update-2016-03-15](url) m'a permis de résoudre le souci.

**Comment by MartinBraquet** [comment]
Le soucis est résolu, merci :).
