### ISSUE TITLE
Traduction de "formulaire"

### ISSUE THREAD

**Issue by Peiffap** [Gp2mv3/Syntheses#473]
Comme mentionné dans la PR #463, la traduction du mot "formulaire" en anglais n'est pas immédiate. Voice un petit résumé des possibilités, dites ce qui vous semble le mieux :

- Cheat sheet

- Reference card

- List of formulas/formulae (et lequel des deux du coup)

- Formulary

- List of equations

- Handbook

- ...

**Comment by anpar** [comment]
Cheat sheet

**Comment by blegat** [comment]
I am also in favor Cheatsheet
