### ISSUE TITLE
Manque de participation extérieure

### ISSUE THREAD

**Issue by blegat** [Gp2mv3/Syntheses#48]
Ce projet manque de participation des autres étudiants que ce soit pour développer des nouvelles synthèses, d'ajouter des synthèses déjà faites à ce projet ou d'améliorer des synthèses existantes en changeant le code ou en reportant un problème.

Je pense que les gens se font une fausse idée en croyant que c'est un projet fait par Gp2mv3 et moi même alors qu'il est ouvert à tout le monde (sinon on aurait du mal à avoir des synthèses de qualité pour toutes les options d'ailleurs :D)

Il faut donc essayer de régler ce problème. Que proposez-vous ?
Je pense qu'une première chose à faire est de réajuster le message en haut de chaque synthèse en ajoutant peut-être certains éléments sur `README` car je pene que beaucoup de gens ne le lisent pas et n'arrivent même pas sur cette page.
Il faudrait aussi ajouter des éléments aux `README`.
Quand au wiki, j'hésite toujours à ajouter des éléments à ce dernier ou au wiki. Je ne sais pas si l'équilibre actuel est bien choisi, qu'en pensez-vous ?

Il faudrait aussi trouver un moyen de démistifier `git`.
Il faut sans doute insister sur le fait qu'il existe des GUI qui rend ça super facile.
On pourra aussi faire un lien vers la partie outil [du livre de systèmes informatique 1](http://sinf1252.info.ucl.ac.be/) une fois qu'elle sera complètée (Matthieu Baerts et moi sommes chargés de le faire fin des vacances). Ça serait bien que l'apprentissage de `git` fasse partie du cours d'informatique 1 :D

Je suis en train de remplacer l'outil `update_dropbox.sh` par un utilitaire que j'ai écrit en python qui est un [projet séparé](https://github.com/blegat/smartcp).

Bref merci de me donner des conseils pour cela comme pour l'issue #44.

**Comment by Peiffap** [comment]
This issue doesn't seem likely to ever be solved, so I'm closing this for the time being.

**Comment by Jimvy** [comment]
Well, I would think it's better to have it open so that newcomers can immediately see that we are asking for their help. But indeed, unlikely to be really solved.
