### ISSUE TITLE
french ou frenchb ?

### ISSUE THREAD

**Issue by MartinBraquet** [Gp2mv3/Syntheses#485]
Dans `eplbase.cls`, on utilise `frenchb` et cela me renvoie un warning car ce package est "deprecated". Ce warning disparait en utilsant `french` à la place, on peut le remplacer par `french`?

**Comment by blegat** [comment]
Oui, il faudrait replacer `frenchb` par `french`

**Comment by MartinBraquet** [comment]
OK, je le push :+1:
