### ISSUE TITLE
Septembre comme mois

### ISSUE THREAD

**Issue by Peiffap** [Gp2mv3/Syntheses#515]
Dans la PR #510, la possibilité de mettre Septembre est enlevée. Il faudrait alors changer les examens de systinfo q4 pour lesquels le mois indiqué est Septembre. Je suis pas sûr par ailleurs que ce soit un meilleur choix de mettre Août comme le prof les a appelés Septembre 201x A/B sur INGInious... Vous en pensez quoi?

**Comment by MartinBraquet** [comment]
Tu voudrais quand même garder le choix de mettre Septembre pour d'autres examens?
Pour les exams de systinfos, moi je laisserais comme ça. Vu qu'ils sont les premiers sur le drive, il n'y a que le dossier `201x_Septembre`qui apparait. Par contre, pour d'autres examens qui ont déjà un pdf sur le drive, par exemple les photos des questions, elles sont dans un dossier `201x_Août`, donc ça poserait problème si quelqu'un crée sur github un document en septembre vu que la synchro va créer un nouveau dossier `201x_Septembre` juste à coté de `201x_Août`.

**Comment by Peiffap** [comment]
En effet. Ici par contre le problème est que comme add.sh n'a plus l'option Septembre, les fichiers ne compilent plus... Sinon en général oui c'est Août qui est utilisé.

**Comment by MartinBraquet** [comment]
Pourquoi ils ne compileraient plus?

**Comment by Jimvy** [comment]
Perso, je suis plutôt favorable à une généralisation de septembre plutôt que août, ce qui permettrait, dans les dossiers du drive, d'avoir les dossiers dans l'ordre chronologique : janvier, puis juin, puis septembre.
Et il suffirait de dire qu'on prend la date des délibérations comme mois de référence, pour ceux qui le demanderaient 😋

**Comment by MartinBraquet** [comment]
Oui pourquoi pas, mais alors il y a 21 dossiers Août sur github à changer en Septembre ...

**Comment by blegat** [comment]
Je pense que le choix de Août viens des Tuyaux EPL

**Comment by Peiffap** [comment]
C'est vrai que de tout mettre en Septembre est une solution élégante... Après si vous aimez plus de mettre tout en Août, c'est bon aussi pour moi mais il me semble que les fichiers systinfo ne compilaient pas à moins d'ajouter un mois au add.sh.

**Comment by MartinBraquet** [comment]
Le bash n'a rien à voir avec la compilation, il crée juste les templates, sous-dossiers et makefiles =).

**Comment by Peiffap** [comment]
Juste, le problème était un problème de création de fichiers.

**Comment by MartinBraquet** [comment]
Any update? On laisserait Août pour finir? :)

**Comment by Jimvy** [comment]
Au pire on laisse tel que c'est pour le moment et on attend d'avoir plus d'avis - on est en comité fermé ici.
Juste pour info, l'idée de mettre septembre vient de toi si j'ai bon souvenir (j'avais vu ça dans les mails ou qlq chose comme ça), et je trouvais ça franchement malin, même si c'est contraire à l'intuition (mais, qu'est-ce qui n'est pas contraire à l'intuition dans cette vie :p )

**Comment by MartinBraquet** [comment]
Oui, j'avais fait un copy-paste d'un document sur le drive.
En réalité, ce serait mieux d'avoir septembre comme mois pour l'ordre chronologique, mais ça impliquerait de changer le nom de 149 dossiers sur le drive et 21 sur ce repo.
Avant, on n'avait accès au drive que sur le onedrive, donc c'était impossible de renommer Aout en Septembre par un programme. Mais maintenant que je peux faire joujou avec le shell en local, il me faut 5 minutes.
Après, il faudrait aussi changer les 21 dossiers de ce repo, c-à-d , pour chacun, renommer un dossier, un makefile, la variable dans le makefile, et les noms des .tex dans le dossiers... Je peux le faire mais il faudrait un peu l'accord d'autres personnes pour être sûr de ne pas avoir de nouvelle idée de changement plus tard.
PS: pour le "comité fermé", je ne suis pas sûr que ça soit dû à la période de vacances, il n'y a pas tellement plus de contributeurs supplémentaires qui surgissent pendant l'année. Il faudrait vraiment avoir plus de gens, il y a plus de 1200 personnes qui ont accès au Drive en 2017-2018, et moins de 10 qui ont fait plus de 5 commits sur cette période, c'est incroyable.

![image](https://user-images.githubusercontent.com/25173236/43250424-9732d47e-90bd-11e8-845c-4fe3c7aaefbd.png)

**Comment by blegat** [comment]
Faisons un sondage:

* Pour Août réagissez avec :+1: 
* Pour Septembre réagissez avec :heart:

**Comment by Jimvy** [comment]
C'est fortement biaisé d'utiliser 👍 et ❤️  😄

**Comment by Jimvy** [comment]
L'autre jour j'ai demandé à 5 (ou 4) amis si c'était ok que je regarde leurs anciennes soumissions INGInious, ils ont vu mais n'ont pas répondu. Donc bon, ça ne veut pas dire grand chose ;)

**Comment by Jimvy** [comment]
(EDIT : la majorité des gens n'ont juste pas envie de répondre en période estivale, ils ne sont pas fous non plus, ils sont en vacances ou en blocus.)

**Comment by MartinBraquet** [comment]
Répondre, ça met 30 secondes.

**Comment by MartinBraquet** [comment]
@blegat , tu penses que je peux renommer août en septembre , après 25 jours de sondage ? :smile:

**Comment by blegat** [comment]
Je pense qu'on peut considérer que Septembre a gagné oui :-P
