### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by Peiffap** [Gp2mv3/Syntheses#525]
Comme dit par @Jimvy dans les PR #484 et #508, il serait bien de définir un style à suivre sur ce repo... Personellement je suis un grand fan des recommendations de Papa Torvalds: https://www.kernel.org/doc/html/v4.10/process/coding-style.html

**Comment by Jimvy** [comment]
Papa Torvalds code en C et en assembleur, et ne rédige pas des synthèses. ;)
(Je suis aussi un fan de ses recommandations.)

1. Comme précisé dans #484 et #513, mon avis sur la longueur des lignes est la suivante :
    1. cette coupure des lignes à 80 caractères est historique, elle était adaptée à une époque où les éditeurs de texte ne savaient pas couper les lignes proprement (2) et où les terminaux pouvaient (devaient ?) afficher 80 caractères par lignes. Maintenant que les éditeurs de textes, et dans ce cas les éditeurs LaTeX, savent correctement couper les lignes lorsque celles-ci dépassent la largeur de la fenêtre, cette limite a moins de sens.
    2. La limite est compréhensible pour du code, qui doit être simple, mais elle n'est pas si utile pour du texte, dans lequel la complexité à comprendre est directement proportionnel au contenu et au nombre de caractères : couper les lignes ne vas pas rendre magiquement le texte plus compréhensible, et ne devrait pas inciter l'auteur à franchement réduire la complexité de ce qu'il écrit. (1) Alors que pour du code, plus la ligne est courte, plus le développeur va probablement tenter de rendre son code plus compréhensible.
    3. Lorsque j'édite du texte LaTeX, j'ai généralement la preview du document à droite, l'arborescence du document à gauche, et parfois deux documents l'un à côté de l'autre. La largeur de la fenêtre passe en dessous de 80 caractères, généralement 60, et on se retrouve avec une alternance entre des lignes qui prennent toute la largeur de l'écran et des lignes qui sont super courtes et qui ne font que compléter les quelques caractères qui restent, souvent seulement 20 ou 30. C'est une horreur.
    4. Il y a une utilité à couper les lignes, et c'est de couper là où la phrase a un changement sémantique (de sens) : par exemple, au niveau des points, points-virgules, deux-points, et virgules s'il s'agit d'une phrase propositionnelle (3), ainsi que les conjonctions de coordinations, et certaines conjonctions de subordination. Ca permet de plus clairement voir la structure de la phrase (et donc, ça participe à une meilleure compréhension du texte, de manière similaire aux lignes de code courtes), et ça a l'avantage, dans Git (4), de permettre une modification de la sous-phrase sans interférer avec les autres sous-phrases (le changement est localisé sur une ligne)

2. Maintenant, mon avis sur la mise en conformance de ces lignes. A savoir, ce qui a été fait dans #484 (couper les lignes à 80 caractères depuis un texte qui utilisait des longues lignes) et dans #513 (fusionner des lignes qui faisaient moins de 80 caractères pour que ça en devienne des longues) :
    1. Se référer au § ci-dessus pour ce qui est du premier cas :p 
    2. Se référer à Torvalds pour tout ce qui concerne la cohérence générale du document : idéalement il ne faudrait avoir qu'un seul style. Mais, c'est idéal et peu pratique.
    3. Changer juste le style d'une ligne fait qu'on peut avoir l'impression que le contenu a changé, alors qu'il n'y a que la mise en page du code source qui a changé, ce qui a peu de sens à être enregistré dans Git. Ca pollue les diffs plus qu'autre chose et ça donne une fausse impression de mise à jour.
    4. Par contre, lorsqu'on se retrouve à apporter des modifications à une ligne existante, pour corriger des fautes, là le changement de style peut s'expliquer et peut s'appliquer (se référer au point 2.ii pour l'opposé de ce principe :p ).

Historiquement, la technique du point 1.iv est celle appliquée aux synthèses des Q1, Q2 etc.
Personnellement, j'essaie d'appliquer la technique du point 1.iv en combinaison avec 2.iv lorsque je modifie un document existant. Lorsque j'en crée un, je pense que je mélange les longues lignes avec 1.iv, ce qui est agaçant, je l'avoue.

(To be extended au fur et à mesure qu'on rajoute des trucs dans la discussion.)

Notes de bas de page :

(1) Une étude de psychologie intéressante pourrait étudier l'impact d'une limitation du nombre de caractères par ligne sur la complexité du texte écrit.

(2) Encore aujourd'hui, vim coupe par défaut à exactement la largeur de la fenêtre, en s'en fichant des mots. Il y a probablement une extension pour cela, j'ai pas encore cherché ^^

(3) Dans la phrase qui précède cette note (celles avec "par exemple"), les virgules ne séparent pas des phrases propositionnelles. Dans cette phrase-ci et dans la note 2, les virgules peuvent séparer ce que j'appellerais des phrases propositionnelles, même si le début de phrase "Encore aujourd'hui" n'est pas vraiment une phrase, j'ai oublié son nom. A noter que dans la phrase avec "par exemple", on pourrait couper au niveau de la virgule qui précède "et virgules", dans la mesure où il s'agit d'un bout de phrase assez longue.

(4) Je rappelle que Git enregistre les modifications au niveau des _lignes_, et pas au niveau des _mots_ ou des _fichiers_ : c'est Github qui les rajoute (et parfois ça plante).

**Comment by Peiffap** [comment]
Je suis d'accord avec toi, en ajoutant que j'aime bien couper avant les 80 caractères quand même, que ce soit sur une ponctuation ou sur une conjonction (les phrases longues sont en général moins bien rédigées, car une seule phrase ne devrait parler que d'un seul concept...).

Sinon, "encore aujourd'hui" est un complément circonstanciel de temps si je ne m'abuse 😉.

**Comment by MartinBraquet** [comment]
Si vous recherchez d'autres avis, moi je suis partant pour suivre le style que vous proposez/proposerez. Dans tous les cas, ce serait utile de le spécifier dans le `readme`.

**Comment by Peiffap** [comment]
With the current administration policy, this issue no longer has a purpose: it's already hard enough to get high-quality additions to the repo as is, and enforcing a certain coding style would take way too much time for the maintainers. I'm thus closing this as it is not relevant anymore.
