### ISSUE TITLE
Changement de code (Réforme du bac)

### ISSUE THREAD

**Issue by MartinBraquet** [Gp2mv3/Syntheses#539]
La réforme du bac commence à la rentrée, et les sigles des cours changent de FSAB à EPL.
On laisserait tout à FSAB sur ce repo et on changerait dans le config.yml le match de FSAB pour qu'il corresponde à EPL, de sorte à avoir le bon chemin pour le drive?

**Comment by Jimvy** [comment]
Comme discuté en MP :
- Pour les nouveaux cours, style LEPL1101 (algèbre), LEPL1102 (analyse I), LEPL1105 (analyse II), LEPL1108 (math discrète et proba), LEPL1109 (stat et datascience), LEPL1401 (info 1 Python), LEPL1402 (info 2 Java), LEPL1501 (P1), LEPL1503 (P3 Q4 info), LEPL1801 (éthique), LEPL1803 (économie), LEPL1804 (devdur), LEPL1805 (gestion personnes) je pense que le mieux est de laisser les futurs étudiants faire leur propre synthèse, vu qu'on ne sait pas trop de quoi sera fait le cours. Et on garderait les anciens fichiers dans le repo, comme on garde les anciennes synthèses actuellement.
- Pour les cours renommés dont le contenu reste identique ou presque (à vérifier), style LEPL1103 (math 3), LEPL1106 (sigsys) LEPL1201, LEPL1202, LEPL1301, LEPL1302, je pense que le mieux est de mettre les documents tels quels dans le Drive (éventuellement changer le config.yaml). On peut les renommer au fur et à mesure qu'ils sont changés, ou tous les renommer. Connaissant Git il a du mal avec l'historique des fichiers renommés dès que ce n'est pas évident, donc le mieux serait de les renommer un commit à la fois.
- Pour les cours renommés mais dont le contenu va changer, style LEPL1104 (methodnum MATLAB->Python), LEPL1110 (fem) et LEPL1502 (P2 qui va probablement un peu changer), j'hésite sur la bonne méthode (num ha ha). Si les changements sont modérés (P2 et fem) ça peut aller de les renommer et de les mettre à jour. Pour méthodnum en fonction de la matière ça peut beaucoup changer ou pas ; a priori il y aura juste les codes matlab qui doivent être traduits.
- Pour les cours d'info qui deviennent wtf (LINFO1104 qui reprend LFSAB1402 + une partie de LINGI1131 ; LINFO1123 qui reprend une partie de LINGI1101 et une grosse partie de LINGI1123), peut-être qu'il vaut mieux appliquer la même stratégie que pour les cours de la première catégorie.

Il faut également tenir compte du fait que tous les cours ne vont pas disparaitre. Par exemple, méthodnum sera présent en double l'année prochaine (bac 1 2018- et bac 2 2017-) ; MMC sera donné en 2019 à la fois au bac 2 2018 et au bac 3 2017, peut-être avec des changements (ça promet d'être marrant) ; les cours spiritueux (euh, oups) seront donnés aux bac 2 2018 et au M2 2015 (nous) ; éco sera donné en Q2 bac 1 2018 et en Q4 bac 2 2017.
(Quand je dis bac 2 2017 ce sont les bac 2 qui sont rentrés en bac 1 en 2017).

By the way, faudrait signaler à l'EPL que la fiche https://uclouvain.be/prog-2018-fsa1ba-formation_generale est incorrecte pour les cours de bac 3 Q2 en fyki.

**Comment by MartinBraquet** [comment]
Je suis d'accord, il faudrait donc changer la variable OPTION dans les makefiles de FSAB à EPL pour les cours qui ne changent pas du tout. De cette manière, les cours qui changent se verront toujours attribuer la variable OPTION à FSAB pour l'ancien et les étudiants créeront un nouveau dossier avec la variable OPTION à EPL pour le nouveau.

**Comment by MartinBraquet** [comment]
Closing to clean my open issues; consider using the Wiki or Projects sections for improvements with no due date.
