### ISSUE TITLE
add.sh ne fonctionne que s'il est exécuté depuis la base du repository

### ISSUE THREAD

**Issue by Jimvy** [Gp2mv3/Syntheses#586]
Appeler `add.sh` depuis un autre dossier provoque la création dans ce dossier d'un dossier `src` contenant les dossiers demandés, avant que `add.sh` finisse par planter lorsqu'il ne reconnait pas le dossier `templates`.

**Comment by Peiffap** [comment]
@Jimvy Fixed by #587 je crois?
