### ISSUE TITLE
Issue with creating notes in add.sh

### ISSUE THREAD

**Issue by Peiffap** [Gp2mv3/Syntheses#589]
Quand j'essaie de créer des notes (en l'occurence mes notes de CM pour le cours d'opti), il me demande de spécifier une variable `sol`, ce qui n'a pas beaucoup de sens selon moi. C'est un comportement désiré ou bien une erreur à fixer? Dans le how_to_contribute, il n'en parlent en tout cas pas...

**Comment by Jimvy** [comment]
C'est une erreur.

**Comment by Peiffap** [comment]
Tu vois où il faut fixer? C'est pas super urgent.

**Comment by MartinBraquet** [comment]
Je ne vois pas de soucis, tu saurais en dire plus @Peiffap ? :wink: 
```
$ ./add.sh 4 opti INMA 1702 notes
Starting:
Create subdirectory...
```

**Comment by Peiffap** [comment]
`
MacBook-Pro-13:Syntheses admin$ ./add.sh 4 opti INMA 1702 notes
Please choose sol among ``only none both''. You chose ``''.
MacBook-Pro-13:Syntheses admin$ 
`
Ah... Peut-être que c'est mac qui se plante?

**Comment by MartinBraquet** [comment]
En fait, il interprète que tu as noté un chaine vide : `You chose ``''`.
J'ai résolu ce bug dans la PR liée au bash (#590), pour ne pas avoir de conflit en créant une nouvelle PR.
