### ISSUE TITLE
Adding remarks at the end of hypertitle

### ISSUE THREAD

**Issue by Peiffap** [Gp2mv3/Syntheses#592]
As mentioned in #584 this feature seems to have stopped working. Would be nice if this can be fixed (just putting it here so I don't forget about it, not an urgent thing).

**Comment by MartinBraquet** [comment]
(Switch in FR)
En mettant des accolades à la fin de `hypertitle`? Je ne rien à ce propos dans l'historique de `epleval.cls`. Tu pourrais taper un exemple ou montrer un .tex qui utilise cette technique? :smile:

**Comment by Peiffap** [comment]
Pour moi aussi ça semblait fonctionner, mais Jean-Martin avait des problèmes avec ça.

**Comment by Jimvy** [comment]
Il y a des exemples dans les examens d'info 1.
(Qui doivent d'ailleurs être mis à jour vu que le Drive a changé... Ce sera une autre PR.)
En fait, ça fonctionne encore... A condition qu'on mette le crochet droit '[' sur la même ligne que les autres arguments de `hypertitle`. Si on revient à la ligne, il ne le prend pas.
Je pense qu'il s'agit d'un bug (du parseur) de LaTeX.

**Comment by MartinBraquet** [comment]
Ok, donc closed ?

**Comment by Jimvy** [comment]
Je corrigerai. Mais oui, closed car LaTeX.

**Comment by Jimvy** [comment]
En fait, l'idée de cette remarque c'est parce que le fichier ne contient pas l'énoncé de l'examen, juste l'énoncé des questions, au contraire d'autres examens sur le site qui ont tout retapé.
Mais je vais plutôt remplacer ce commentaire par un disant que des codes sources sont disponibles sur Github.
