### ISSUE TITLE
Espaces autour de la ponctuation cassés au sein du texte optionnel de hypertitle

### ISSUE THREAD

**Issue by Jimvy** [Gp2mv3/Syntheses#597]
Cf examen d'info 1 de juin 2013 : il n'y a pas d'espace avant le point-virgule de la dernière ligne, en tout cas sous TeXlive 2017. Ca n'a pas beaucoup de sens alors que le document est en français partout ailleurs.
I'll have a look at it tandis que je corrige les (nombreux) soucis de listings, des solfig etc...

**Comment by Peiffap** [comment]
C'est précis comme issue 😄

**Comment by Jimvy** [comment]
C'est aussi très précis comme erreur ;)

**Comment by MartinBraquet** [comment]
![image](https://user-images.githubusercontent.com/25173236/44630624-e3e21800-a960-11e8-8804-296ca763aa92.png)
Je vois un espace, il devrait y en avoir un ou pas? Quel est le rapport avec le français?

**Comment by Jimvy** [comment]
Oui, c'est le cas sur master car il y avait bien une espace avant le point-virgule.
J'ai fait des changements et je l'ai enlevé, car il est superflu (babel frenchb s'en charge).
Chez moi je n'ai pas droit à l'espace avant le point-virgule.

**Comment by Jimvy** [comment]
Il apparait que toutes les fonctionnalités de babel-french fonctionnent dans la page de garde et dans le texte optionnel, à l'exception des espaces devant la ponctuation haute ':', ';', '?' et '!'.
Pour que ces caractères deviennent "actifs" et insèrent une espace insécable, il faut que le texte soit déclaré après le `\begin{document}`. En particulier, ils ne sont pas actifs lorsqu'ils sont déclarés dans le `DeclareDocumentCommand{hypertitle}{...}`, car *même* si le `\begin{document}` apparait avant le texte, la commande, et donc la suite de caractères définissant le texte etc, est défini *avant* que le `\begin{document}` soit exécuté, et donc avant que les caractères ne deviennent actifs.
D'après ce que je comprends, il n'y a que deux solutions :
- Soit mettre le `\begin{document}` avant le `\DeclareDocumentCommand`, mais je n'ai pas trouvé de manière de le faire marcher.
- Soit encadrer le texte pouvant contenir des caractères à activer dans `\begingroup\shorthandon{;:!?} <le texte> \shorthandoff{;:!?}\endgroup`. Ceci a le risque de provoquer d'autres soucis dans le futur, car je devine que certaines commandes de certains packages vont casser si elles sont utilisées dans ce groupe.
A mon avis, la meilleure solution reste juste de give up, vu que :
- toutes les autres commandes et features de babel-french fonctionnent correctement;
- on peut insérer une espace insécable en écrivant `a~: b`, donc il est possible d'aboutir au bon résultat.
Ca pourrait néanmoins valoir la peine d'être mentionné dans une éventuelle documentation du repo.
