### ISSUE TITLE
Rename ML folder

### ISSUE THREAD

**Issue by Peiffap** [Gp2mv3/Syntheses#604]
As discussed (well, observed) in #603.

**Comment by Jimvy** [comment]
Mais quels noms leur donner ? Pour rappel :
- LINGI2262 Machine Learning: classification and evaluation, avec Pierre Dupont, en Q2
- LELEC2870 Machine Learning: regression, dimensionality reduction and data visualization, avec John Lee et Michel Verleysen, en Q1
Ca ne pose pas de problème au niveau des dossiers ici, mais ça pose problème dans le cas du mapping car on ne saura pas trop quel nom de dossier attribuer.
Pour le moment le premier se trouve dans le dossier "INFO>Q8>Intelligence artificielle, Apprentissage et reconnaissance", qui est selon moi l'ancien nom du cours. Le deuxième se trouve dans le dossier "ELEC>Q7>Machine Learning".
Peut-être que le mieux serait de les appeler tous les deux "Machine Learning", tout en sachant que ce sont deux cours différents ? Ou alors on peut appeler l'un "ml-ingi" et l'autre "ml-elec" pour la flexibilité.

**Comment by Peiffap** [comment]
Je pensais le faire en plus simple: `mlce` et `mlrdd`.

**Comment by Jimvy** [comment]
Je trouve ça très difficile à lire.
Essentiellement, les cours traitent de machine learning, puis ajoutent des trucs dans leur titre pour donner envie de prendre le cours (littéralement : du machine learning ça a besoin de régression, de réduction, de classification et d'"evaluation").

**Comment by Peiffap** [comment]
En y réflechissant, je me dis que "ml-ingi/elec" est le meilleur choix.

**Comment by Peiffap** [comment]
Having thought some more about it, my last solution would introduce redundancy in the name ("ml-elec-ELEC2870"), which is not very nice. Just calling both of them "ml" is fine, seen as the actual class code is appended to it, and that they are in different folders. Hence, I'm closing this.
