### ISSUE TITLE
Compiler une solution de test/examen uniquement si begin{solution}

### ISSUE THREAD

**Issue by MartinBraquet** [Gp2mv3/Syntheses#630]
L'utilisation de l'attribut `SOl` dans les makefiles n'est pas très pratique puisque celui-ci devrait changer par exemple en cas d'ajout d'un correctif à un examen (alors que le document était initialement créé sans solution: `SOL=NONE`).
Il faudrait compiler les solutions d'un document uniquement si `begin{solution}` est utilisé dans le fichier tex.

**Comment by Jimvy** [comment]
Dans la même catégorie : je me disais que ce serait bien d'imposer l'usage de `\begin{solution} ... \end{solution}` ou de `\nosolution` en faisant en sorte de faire planter la compilation en cas de non-usage de ces commandes. J'avais une idée de comment arranger ça, vu que c'est similaire à un autre fix (en attente depuis plus d'un mois, je devrais penser à la PR).

**Comment by Jimvy** [comment]
Après relecture, je trouve aussi que l'attribut SOL ne sert à rien (ou presque), vu qu'il change dès que quelqu'un ajoute une solution, et qu'il porte à confusion lors de la création d'un document.
- SOL=only est très rare et signifie qu'on doit utiliser des \nostatement
- SOL=none change dès qu'on ajoute une solution

Le mieux serait d'analyser le code source et d'en déduire s'il y a les énoncés/les solutions. C'est plus complexe à gérer dans le root.mk, mais ça simplifie l'interface lors de l'ajout d'examens.

**Comment by Peiffap** [comment]
@MartinBraquet What is the state of this issue after merging #709?

**Comment by MartinBraquet** [comment]
It's not checked in root.mk but I think it's enough with the provided template, people should not forget to add a (no-)sol section.

**Comment by MartinBraquet** [comment]
Closing to clean my open issues; consider using the Wiki or Projects sections for improvements with no due date.
