### ISSUE TITLE
Fichiers superflus sur le Drive

### ISSUE THREAD

**Issue by Peiffap** [Gp2mv3/Syntheses#651]
Depuis qu'on ajoute "majeure" ou "mineure" après les examens, il y a des fichiers superflus (sans maj/min) sur le Drive, comme par exemple pour les examens d'INGI1101-logique, dans le Q5 d'INFO.

Il serait intéressant d'enlever ces fichiers, car ils pourraient prêter à confusion.

**Comment by MartinBraquet** [comment]
Ok, ceux qui voient d'autres déchets peuvent le signaler ici. :smile:

**Comment by Peiffap** [comment]
As this issue is not directly related to the repo, closing. Drive admins have been made aware of the issue.
