### ISSUE TITLE
LFSAB1302 - Examen de Août 2016 - erreur

### ISSUE THREAD

**Issue by gorfou99** [Gp2mv3/Syntheses#655]
Dans la question 2, la ligne `p_{CS_2} = X_{CS_2} * 68.66 kPa = 38.02 kPa` n'est pas correcte
Ca devrait être `p_{CS_2} = X_{CS_2} * 68.66 kPa = 37.76 kPa` (car `X_{CS_2}=0.55`)

Et de même ça devrait:
`p_{CH_3COCH_3} = X_{CH_3COCH_3} * 44.26 kPa = 19.92 kPa` (car `X_{CS_2}=0.45`)

**Comment by MartinBraquet** [comment]
Merci, c'est possible que tu le corriges toi-même? Il devrait même y avoir moyen directement sur Github vu que ce sont des changements mineurs. :smile:

**Comment by gorfou99** [comment]
@Peiffap oui petite faute. J'essaierai de corriger après l'examen

**Comment by Peiffap** [comment]
C'est car Louis avait arrondi pour les fractions molaires :), les valeurs données sont correctes.
