### ISSUE TITLE
Wrong hypertitle fill-in on macOS

### ISSUE THREAD

**Issue by Peiffap** [Gp2mv3/Syntheses#681]
When creating new documents, the hypertitle is now automatically set to contain the name of the course instead of its code. However, for macOS users, the following happens for almost every course that has a nonstandard character in it, i.e., most french titles. For example, 
>Méthodes de conception de programmes

becomes
>b'Mxc3xa9thodes de conception de programmes'

which is not really wanted behaviour...

**Comment by Jimvy** [comment]
I have a similar problem, but the output is "b'MÃ©thodes numÃ©riques'"

**Comment by MartinBraquet** [comment]
Not on Linux. :smile:

**Comment by Jimvy** [comment]
Bon, c'est clairement un problème de terminaux : vous utilisez quels terminaux sur chacun ? Et leur encodage ?
Tapez "env"
Chez moi, j'ai :
- Git Bash : LANG="en_US.UTF-8", TERM="xterm". Sur ce terminal, ma correction fonctionne. A noter qu'il utilise le "python" (alias Python 3) de Windows.
- Ubuntu 18.04 Bash : LANG="C.UTF-8", TERM="xterm-256color". Sur ce terminal, le script Python n'est jamais lancé, notamment parce que depuis Ubuntu 18.04, "python" (alias Python 2) n'existe plus par défaut, et est remplacé par "python3" (alias Python 3).

**Comment by Peiffap** [comment]
Moi j'ai LC_CTYPE=UTF-8 et TERM=xterm-256color.

________________________________

**Comment by MartinBraquet** [comment]
LANG=en_GB.UTF-8.
