### ISSUE TITLE
Amélioration de "How to contribute"

### ISSUE THREAD

**Issue by MartinBraquet** [Gp2mv3/Syntheses#689]
Après discussion avec un autre étudiant, le document _How to contribute_ n'est pas assez user-friendly pour les novices de Git.
Il faudrait ajouter une description complet, pas-à-pas et avec des screenshots à chaque étape, détaillant la manière de proposer un fichier .tex via une PR sur le master officiel (çad depuis le clone de repo officiel en local jusqu'au push sur la branche online et ainsi l'ajout de la PR).
Pour le moment, l'usage des lignes de commande est bien trop vague pour la majorité des utilisateurs de Windows...

**Comment by Jimvy** [comment]
Je suis d'accord que c'est peu user-friendly.
Mais j'ai quand même des doutes que ce soir à nous de leur apprendre l'usage de GitHub...
Par contre, ça peut valoir la peine d'expliquer comment marchent `add sh`.
Et on ne m'empêchera pas de dire que l'usage du terminal n'est pas si compliqué que ça, et que c'est un outil tellement utile et tellement nécessaire dans la suite des études (je pense aux projets en C, à l'option en info, aux master Élec, Elme et Info, etc) que ça ne peut pas faire de mal de déjà l'apprendre.
(Et Git Bash sous Windows fonctionne très bien. 😛)
