### ISSUE TITLE
ELEC1370-2013-Juin-Majeure-Question 1:Phaseurs

### ISSUE THREAD

**Issue by alex-1211** [Gp2mv3/Syntheses#692]
Le symbole de la source de tension est inversé (la borne positive devrait être vers le haut)

**Comment by Jimvy** [comment]
C'est un bug dû à circuitikz, après qu'ils aient changé l'API.

**Comment by alex-1211** [comment]
En fait il y a un tas de bugs comme ça dans les examens de cirmes. Je peux toutes les lister, mais le mieux est de se référer au document "Examens_ELEC1370.pdf" où a priori tous les schémas sont corrects

**Comment by alex-1211** [comment]
En fait presque tous les schémas des exams de circmes sont erronés à cause de ce bug

**Comment by Jimvy** [comment]
Oui, il faut corriger toutes les instances de circuitikz, car je pense que le problème est aussi présent en physique 1.

**Comment by MartinBraquet** [comment]
StackExchange propose de faire `\usepackage[oldvoltagedirection]{circuitikz}` en header pour un quick fix, qu'en pensez-vous ?
