### ISSUE TITLE
Ajout d'une synthèse: Relativité restreinte [PHYS1231]

### ISSUE THREAD

**Issue by MiguelDLC** [Gp2mv3/Syntheses#700]
Bonjour,
Quelques personnes du cours de relativité restreinte ont fait une synthèse (qui se trouve sur actuellement overleaf). 
J'aimerais la porter sur le drive, et je me demande quelles sont les étapes à suivre, autre que créer le dossier dans l'endroit approprié en respectant les conventions sur les noms de cours. (Je proposerais `Q4 > relatrestreinte-PHYS1231 > summary > relatrestreinte-PHYS1231-summary.tex`, mais )

Par exemple, je ne saisis pas encore le fonctionnement du système de compilation, des Makefile et des fichiers .mk. Et je suis d'accord avec @Jimvy , ça peut valoir la peine d'expliquer comment marche `add.sh` (je n'ai aucune idée de ce que c'est)

Autre question, je suppose que les pdf sont compilés avec pdfLaTeX, et non LuaLaTeX? (La synthèse d'oveleaf sort une flopée d'erreurs quand on la compile avec pdfLeTeX)

**Comment by Peiffap** [comment]
Hello,


En fait, la création du dossier (et tout ce qui vient avec, genre créer les fichiers pour la compilation et ce bazar), c'est justement ce que fait `add.sh`. Pour le faire, tu te mets à la racine du repo, et tu suis la convention donnée dans les exemples: dans ton cas, ça deviendrait (je pense) `bash add.sh 4 relatrestreinte PHYS 1231 summary`. Tu peux choisir le nom que tu veux entre `4` et `PHYS`, du coup essaie de prendre le nom que les étudiants y donnent quand ils en parlent (c'est toujours plus logique). Ensuite, tu peux naviguer dans le dossier `q4/relatrestreinte-PHYS1231/summary` avec la commande `cd`, puis tu peux compiler avec `make pdf`. Si tout va bien, tu devrais alors avoir le pdf dans ce dossier.

Ensuite, pour la compilation, on utilise bien pdfLaTeX. Si tu vois des erreurs, ce serait cool d'essayer de les fixer. Par expérience, il y a toujours un workaround. Si tu ne te sens pas chaud de le faire (je ne sais pas à quel point la synthèse est longue, ni combien d'erreurs il y a), c'est toujours cool d'au moins poster le lien dans une issue GitHub, pour que quelqu'un le fasse un jour (on peut espérer...).

tl;dr:
Tu ne dois pas créer ces trucs toi-même, c'est à ça que sert `add.sh`. Les autres fichiers, c'est pour pouvoir compiler les documents, ce que tu peux faire avec `make pdf` à partir du dossier `.../summary`. Quant à l'engine LaTeX, ce serait vraiment long à changer.


Si t'as d'autres questions, hésite vraiment pas; c'est pas tous les jours qu'on a des nouveaux contributeurs sur ce repo 😄 !

**Comment by MartinBraquet** [comment]
Salut Miguel,
J'ajouterais que le document How to Contribute a été mis à jour il y a peu, il pourrait donc t'aider si ce n'est pas déjà le cas. Il est dans le dossier principal de l'EPL-Drive.
Ensuite, si tu ne le sais pas déjà, tu n'as pas besoin de mettre la synthèse en pdf sur le drive vu que tu la mets ici sur Github. Quand la synthèse sera acceptée ici, je lancerai un code qui va automatiquement compiler et mettre le pdf sur le drive.
Comme c'est un nouveau cours, en plus de lancer add.sh, il faut ajouter le nom du cours dans src/config.yml: aux alentours de la ligne 345 de ce fichier, ajoute une ligne avec 
`relatrestreinte: Relativité restreinte`.

**Comment by MiguelDLC** [comment]
Merci pour ces infos. J'ai réussi à faire à peu près tout à part la partie `make pdf`. Je suis sensé taper ça sur git pour générer le pdf ou bien j'ai manqué quelque chose? (Pour l'instant je visualise le pdf en le compilant via texmaker)
Autre question, au moment de la compilation finale qui crée le pdf sur le drive, c'est `config.yml` qui sert à donner le chemin d'accès? 
Sinon question template, début du pdf commence avec "[...] l’excellent cours donné par Jean-Marc Gérard **à l’EPL (École Polytechnique de Louvain)**, [...]", ce qui n'est, strictement parlant, pas juste. Il y a un moyen facile de changer ça ou bien tant pis?
En enfin, est-ce qu'il vaut mieux que je fasse des pull requests fréquents avec les modifications ajoutées (par exemple autour de chaque chapitre), ou plutôt quand la synthèse est terminée?

**Comment by MartinBraquet** [comment]
Ce n'est pas obligé d'utiliser `make pdf`, tu peux tout faire avec Texmaker.
Oui, c'est config.yml qui donne le chemin vers le drive EPL.
Pour la page de garde, c'est compliqué de la changer, je pense qu'on peut la laisser comme ça =).
C'est mieux de mettre la synthèse complète quand elle est finie, selon moi.
Bon travail !

**Comment by MartinBraquet** [comment]
Related to #731 .
