### ISSUE TITLE
[EPL1101] Ajout de la méthode des cofacteurs

### ISSUE THREAD

**Issue by MartinBraquet** [Gp2mv3/Syntheses#757]
La méthode des cofacteurs n'est pas dans la synthèse d'EPL1101, ce document proposé par un étudiant pourrait y être intégré.
[Synthèse méthode des cofacteurs.docx](https://github.com/Gp2mv3/Syntheses/files/3991358/Synthese.methode.des.cofacteurs.docx)
@pdan1 , si tu as le temps, ce serait super =)

**Comment by pdan1** [comment]
Je l'ajoute dans ma liste des tâches, je ferai un PR quand ce sera fait ;)

**Comment by MartinBraquet** [comment]
Closing to clean my open issues; consider using the Wiki or Projects sections for improvements with no due date.

**Comment by Peiffap** [comment]
@MartinBraquet What are the odds I was going to do the exact same thing (clean my open issues/PRs) today... Do you know if the Drive is still being maintained/updated?

**Comment by MartinBraquet** [comment]
No idea, it's been quite a few years since I've seen it or even heard about it. My hunch would be that some folks are still adding PDF files every so often, but without fine-grained peer review.
