### ISSUE TITLE
LMECA1901 : Exam Janvier Mineure Question 3 Partie 2 Sous-Question 3

### ISSUE THREAD

**Issue by louisvbst** [Gp2mv3/Syntheses#768]
Le tableau de correspondance entre X et x est faux. Les erreurs sont les suivantes 
La 3e colonne est par exemple fausse. Le x correspond à X= (L_0 , L_0 , 0). 
La 4e colonne est fausse. Le X correspondant au petit x est X=(0 , L_0 , 0)

**Comment by louisvbst** [comment]
J'ai oublié de préciser que c'était l'examen de janvier 2019

**Comment by MartinBraquet** [comment]
Merci !
Il n'y a pas d'autre erreur dans cet exam ?

**Comment by louisvbst** [comment]
Je n'en ai pas vue d'autre pour l'instant
