### ISSUE TITLE
LFSAB1105 : Exam Janvier 2017 Question 1.1

### ISSUE THREAD

**Issue by louisvbst** [Gp2mv3/Syntheses#775]
x_alpha vaut 8h39 et non 7h39! La réponse finale est donc 13h09 au lieu de 12h09

**Comment by MartinBraquet** [comment]
Merci, peux-tu clarifier ton raisonnement. J'obtiens: 
x_alpha = sigma * 1.645 + mu
              = sqrt(30) * 1.645 + 7h30 = 7h39

**Comment by louisvbst** [comment]
Comme c'est compté en heures, c'est x_alpha=sqrt(0.5)*1.645+7.5=8.66, qui correspond bien à 8h39

**Comment by MartinBraquet** [comment]
Je vois, mais sigma^2 ne vaut pas 0.5, c'est 30 [min^2] donc 30/60^2 [h^2].
Je pense que l'énoncé voulait dire sigma = 30 min, ce sera plus simple.
Tu confirmes que l'on a alors x_alpha = 0.5 * 1.645 + 7h30 = 8h19 ?

**Comment by louisvbst** [comment]
Pourtant dans l'énoncé il est bien indiqué sigma²= 30 minutes. Mais je suis d'accord qu'au niveau unités ça prête à confusion
