### ISSUE TITLE
\abs cannot be put into an exponent without putting {} around it, and other similar issues

### ISSUE THREAD

**Issue by Jimvy** [Gp2mv3/Syntheses#778]
https://github.com/Gp2mv3/Syntheses/blob/351291e8825cb9657231af370f03e2dfb3c759e5/src/eplcommon.sty#L38
The following code crashes:
```latex
\[0^\abs{M_1}\]
``
A working version is:
```latex
\[0^{\abs{M_1}}\]
```
which is ugly. A fix can be to change the definition of `\abs` to:
```latex
\newcommand{\abs}[1]{{\left\lvert#1\right\lvert}}
```
I'm probably going to fix this in an upcoming PR, but I guess there are other potential problems in eplcommon.sty

**Comment by Peiffap** [comment]
@Jimvy This should be fixed by #793.

**Comment by Jimvy** [comment]
I left it open due to the "other similar issues", but I think we can close
it.

**Comment by Peiffap** [comment]
In that case, I'm closing this; it's bad form anyway to typeset nontrivial operations without the curly braces.
