### ISSUE TITLE
Désactiver Greetings.yml

### ISSUE THREAD

**Issue by Jimvy** [Gp2mv3/Syntheses#804]
Cette fonctionnalité ne marche pas des masses : elle n'a fonctionné correctement que deux fois au plus, et pour les nouveaux contributeurs, lorsqu'elle plante, elle affiche un message rouge qui donne l'impression qu'il y a des problèmes dans la PR, et lorsque celle-ci est bonne, elle indique un message en vert, qui peut donner l'impression que tout est OK, ce qui risque de mettre un peu trop en confiance.
En plus, la tâche s'exécute à chaque push effectué, et prend 30 secondes (!) à s'exécuter. C'est pas très cool pour la planète.
Enfin, on répond quand même "assez vite" aux PR et aux issues, ce qui fait qu'on dit déjà "bonjour" aux nouveaux contributeurs.
Donc, je pense qu'on peut désactiver cette fonctionnalité.

**Comment by MartinBraquet** [comment]
Oui clairement, à suivre les updates pour voir s'ils intègrent un jour des checks de compil LaTeX (facile à déployer pour ce repo).
Tu le supprimes ?

**Comment by Jimvy** [comment]
Est-ce qu'il suffit de juste virer le greetings.yml, ou est-ce qu'il y a d'autres paramètres dans le repo à régler ? Vu que c'est une intégration, ça a d'habitude une foultitude de paramètres.

**Comment by MartinBraquet** [comment]
Oui, il faut juste supprimer le fichier

**Comment by Peiffap** [comment]
Fixed by #814.
