### ISSUE TITLE
Erreur solution Juin 2019 - 1d  - Analyse I

### ISSUE THREAD

**Issue by Hokkaydo** [Gp2mv3/Syntheses#895]
Apparemment le correctif serait mauvais, une correction du correctif aurait été posté sur le moodle analyse I (voir avec un bac1)

**Comment by ldevillez** [comment]
Hello @Hokkaydo !
Je n'ai pas vu sur le git de résolution d'examen pour Analyse 1 donc j'ai été voir sur le drive et je ne trouve uniquement le document de moodle. Donc est-ce que tu aurais plus d'infos sur le soucis ?

**Comment by Hokkaydo** [comment]
Whoops, je viens de me renseigner et j'ai mal compris. 
C'était pas janvier 2019 mais juin 2019. 
L'erreur se situe au niveau des conditions frontières, les signes étaient inversés. 
![Correction](https://user-images.githubusercontent.com/42278077/213157887-a3d87e3c-1f2f-444c-94f7-3247186b50ba.png)
Dans l'ancienne version, les 1/2 et -1/2 étaient inversés et le correctif (faux) indiquait qu'on convergeait pour -R <= x < R or on converge pour -R < x <= R

Je ferai une PR si j'ai le temps d'ici ce week-end mais voilà le fichier corrigé 
[LEPL1102-Examen-juin-2019-corrige.pdf](https://github.com/Gp2mv3/Syntheses/files/10445322/LEPL1102-Examen-juin-2019-corrige.pdf)
